<h2>Page Menu</h2>
<h3 class="wide">Edit and Update Page Content</h3>
<form method="post" id="pageForm" name="pageForm"  class="form-horizontal well"
      action="<?php echo $this->currentUrl(); ?>">
  <fieldset>
    <legend class="f_legend">Static Page Content</legend>

    <div class="control-group">
      <label for="static_id" class="control-label">Content Type</label>
      <div class="controls">
        <?php echo $this->static_id ?>
      </div>
    </div>

    <div class="control-group">
      <label for="content" class="control-label">Content</label>
      <div class="controls">
        <textarea name="pageContent" id="pageContent" cols="5" rows="5">
          <?php echo $this->htmlDecode($this->content) ?>
        </textarea>
      </div>
    </div>

      <div class="control-group">
      <div class="controls"><input type="submit" value="save" class="btn btn-success" />
      </div>
    </div>

  </fieldset>

</form>
<?php $this->placeholder('jsInline')->captureStart(); ?>
<?php
$js_link = array('tiny_mce/tiny_mce_popup', 'tiny_mce/tiny_mce');
echo $this->jsView(2, $js_link);
?>
<script type="text/javascript">
  $(function(){
    tinyMCE.init({
      theme : "advanced",
      mode : "textareasc",
      width : "800",
      height : "500",
      plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",
      theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,styleselect,formatselect,fontselect,fontsizeselect,image",
      theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,cleanup,help,code,|,preview,forecolor,backcolor",
      theme_advanced_buttons3 : "insertlayer,moveforward,movebackward,absolute,|,styleprops,|,cite,abbr,acronym,del,ins,attribs,|,visualchars,nonbreaking,template,pagebreak,restoredraft",
      theme_advanced_toolbar_location : "top",
      theme_advanced_toolbar_align : "left",
      theme_advanced_statusbar_location : "bottom",
      theme_advanced_resizing : true,
      template_external_list_url : "lists/template_list.js",
      external_link_list_url : "lists/link_list.js",
      external_image_list_url : "lists/image_list.js",
      media_external_list_url : "lists/media_list.js",
      style_formats : [
        {title : 'Bold text', inline : 'b'},
        {title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
        {title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
        {title : 'Example 1', inline : 'span', classes : 'example1'},
        {title : 'Example 2', inline : 'span', classes : 'example2'},
        {title : 'Table styles'},
        {title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
      ]
    });
    tinyMCE.execCommand('mceAddControl', false, 'pageContent');    
  });
</script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>