<?php $this->placeholder('styles')->captureStart(); ?>
    <link href="<?php echo $this->scriptUrl('/styles/table-css.php'); ?>" 
          rel="stylesheet" type="text/css" />
<?php $this->placeholder('styles')->captureEnd(); ?>

<!-- print out any message from create/saved page proccess -->
<?php 
    if (!empty($this->message)) {
        foreach ($this->message as $warn) echo $this->flashMessage($warn);
    }
?>

<h2>Page Menu</h2>
<h3 class="wide">Update from the list</h3>

<div class="table-container">
	<br class="clearfloat"  />
    <?php if(count($this->paginator)>0) :?>
            <br class="clearfloat"  />
            <table style="width:100%;" cellspacing="0" class="table table-stripped table-bordered">
            <?php echo $this->partial('page/table-header.phtml') . "\n"; ?>
                <tbody>
                    <?php $row_index = 0; ?>                        
		            <?php echo $this->partialLoop('page/table-row.phtml', $this->paginator) . "\n"; ?>
                </tbody>
            </table>
            <br class="clearfloat"  />
	<?php endif; ?>
</div>

<?php $this->placeholder('jsInline')->captureStart(); ?>
<script type="text/javascript">
    $(function(){ $('.filter-panel').show(); });
</script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>