<tr>
    <td><?php echo $this->HtmlDecode($this->username);    ?></td>
    <td><?php echo $this->HtmlDecode($this->date);        ?></td>
    <td><?php echo $this->HtmlDecode($this->module);      ?></td>
    <td><?php echo $this->HtmlDecode($this->action);      ?></td>
    <td><?php echo $this->HtmlDecode($this->language_id); ?></td>
    <td><?php echo $this->HtmlDecode($this->content_id);  ?></td>
</tr>