<?php
$controller_name = Zend_Controller_Front::getInstance()
                ->getRequest()->getControllerName();
$cmsURL = $this->rootUrl() . '/admin/ajax/imagebrowser/type/' . $controller_name;
?>

<script type="text/javascript" src="<?php echo $this->scriptUrl('/lib/tiny_mce/tiny_mce.js') ?>"></script>
<script type="text/javascript">
  tinyMCE.init({
    theme : "advanced",
    mode : "textareas",
    convert_urls : false,
    width : '100%',
    height: 350,
    file_browser_callback : 'myFileBrowser',
    plugins : "pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount,advlist,autosave",
    theme_advanced_buttons1 : [
      "bold",
      "italic",
      "underline",
      "strikethrough",
      "|",
      "justifyleft",
      "justifycenter",
      "justifyright",
      "justifyfull",
      "|",
      'bullist',
      'numlist', 
      'table',
      'image',
      "link",
      "unlink",
      "|",
      'print',
      'preview',
      "fullscreen",
      "code"
    ],
    theme_advanced_buttons2 : [
      "indent",
      "outdent",
      'blockquote',
      "|",
      "forecolor",
      "backcolor",
      "|",
      "formatselect",
      "fontselect",
      "fontsizeselect",
    ],
    theme_advanced_toolbar_location : "top",
    theme_advanced_toolbar_align : "left",
    theme_advanced_statusbar_location : "bottom",
    theme_advanced_resizing : true,
    template_external_list_url : "lists/template_list.js",
    external_link_list_url : "lists/link_list.js",
    external_image_list_url : "lists/image_list.js",
    media_external_list_url : "lists/media_list.js",
    style_formats : [
      {title : 'Bold text', inline : 'b'},
      {title : 'Red text', inline : 'span', styles : {color : '#ff0000'}},
      {title : 'Red header', block : 'h1', styles : {color : '#ff0000'}},
      {title : 'Example 1', inline : 'span', classes : 'example1'},
      {title : 'Example 2', inline : 'span', classes : 'example2'},
      {title : 'Table styles'},
      {title : 'Table row 1', selector : 'tr', classes : 'tablerow1'}
    ]
  });
  
  function myFileBrowser (field_name, url, type, win) 
  {
    var cmsURL = '<?php echo $cmsURL ?>';
    if (cmsURL.indexOf("?") < 0) {
      //add the type as the only query parameter
      cmsURL = cmsURL + "?type=" + type;
    }
    else {
      //add the type as an additional query parameter
      // (PHP session ID is now included if there is one at all)
      cmsURL = cmsURL + "&type=" + type;
    }
    
    tinyMCE.activeEditor.windowManager.open({
      file : cmsURL,
      title : 'My File Browser',
      width : 800,  // Your dimensions may differ - toy around with them!
      height : 550,
      resizable : "no",
      popup_css : false,
      inline : "yes",  // This parameter only has an effect if you use the inlinepopups plugin!
      close_previous : "no"
    }, {
      window : win,
      input : field_name
    });
    return false;
  }
</script>

