

<tr>
    	<td>
        <table class="cleartable">
            <tr><td><a href="<?php echo $this->rootUrl(); ?>/admin/tourismoperator/edit/id/<?php echo $this->tourismoperator_id; ?>/lang/1"><?php echo $this->name; ?></a></td></tr>
            <tr>
                <td>
                    <table class="cleartable mini">
                        <tr>
                            <td><a class="general-remove" href="<?php echo $this->rootUrl(); ?>/admin/tourismoperator/edit/id/<?php echo $this->tourismoperator_id; ?>/lang/1">Edit</a></td>
                            <td><div class="general-remove" onclick="deleteTourism(<?php echo $this->tourismoperator_id; ?>);">Delete</div></td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </td>
    <td><?php echo $this->pointX; ?>, <?php echo $this->pointY; ?></td>
    <td><?php echo $this->areaName($this->area_id);?></td>
    <td>
        <?php $class_list = $this->ClassificationList($this->tourismoperator_id); ?>
        <?php foreach($class_list as $class_name): ?>
        <div class="classification_list"><?php echo $class_name; ?></div>
        <?php endforeach;?>
    </td>

    <td>
        <table class="cleartable">
            <tr><td><a>Indonesian Translation</a></td></tr>
            <tr>
                <td>
                    <table class="cleartable mini">
                        <tr>
                            <td><a class="general-remove" href="<?php echo $this->rootUrl(); ?>/admin/tourismoperator/edit/id/<?php echo $this->tourismoperator_id; ?>/lang/2"><?php $this->CheckTourismIndo($this->tourismoperator_id, 2)?></a></td>
                            <?php $indtrans = $this->CheckTourismIndoTrans($this->tourismoperator_id, 2);
                                  if($indtrans == true){?>
                            <td><div class="general-remove" onclick="deleteTourism2(<?php echo $this->tourismoperator_id; ?>);">Delete</div></td>
                            <?php } ?>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </td>

   
</tr>