<div class="row-fluid">
  <form action="" method="post" enctype="multipart/form-data">
    <div class="control-group">
      <label for="title" class="control-label">Judul</label>
      <div class="controls">
        <?php echo $this->form->title; ?>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span8">
        <div class="control-group">
          <div class="controls">
            <?php echo $this->form->content; ?>
          </div>
        </div>
      </div>
      <div class="span4">
        <div class="control-group well">
          <div class="controls">
            <div class="fileupload fileupload-new"
                 data-provides="fileupload">
              <div class="fileupload-new thumbnail"
                   style="width:200px;height:150px">

                <?php if (isset($this->image)): ?>
                  <img src="<?php echo $this->image; ?>" alt="" />
                <?php else: ?>
                  <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=Direkomendasikan+500x300"   alt="" />
                <?php endif; ?>

              </div>
              <div class="fileupload-preview fileupload-exists
                   thumbnail"
                   style="width:200px;height: 150px">
              </div>
              <div>
                <?php
                $disabled = '';
                if ($this->form->image->getAttrib('disabled') == true)
                  $disabled = 'disabled';
                ?>
                <div class="btn btn-file <?php echo $disabled ?>">
                  <span class="fileupload-new">Pilih Gambar</span>
                  <span class="fileupload-exists">Ganti</span>
                  <?php echo $this->form->image; ?>
                </div>
                <a href="#" class="btn fileupload-exists"
                   data-dismiss="fileupload">Hapus</a>
              </div>

            </div>
          </div>
        </div>
        <div class="control-group well">
          <label for="publish_date" class="control-label">
            Tanggal Terbit </label>
          <div class="controls">
            <?php echo $this->form->publish_date; ?>
          </div>
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <?php echo $this->form->draft; ?>
      <?php echo $this->form->submit; ?>
    </div>
  </form>
</div>

<?php echo $this->render('partial/tinyMCE.phtml'); ?>
<script type="text/javascript">
  $(function(){
    $("#news-publish_date").datepicker({
      dateFormat: 'dd-mm-yy'
    });
})
</script>