<form method="post" action="<?php echo $this->currentUrl();?>" id="photoessayForm" name="photoessayForm">
<fieldset class="wide">
<legend>Photo Essay Information</legend>
    <table>
        <tbody>
            <tr>
                <td><label>Title</label></td>
                <td>&#58;</td>
                <td>
					<?php echo $this->form->photoessay_title; ?>
				</td>
            </tr>
            <tr>
                <td><label>Category</label></td>
                <td>&#58;</td>
                <td>
					<select id="essay-category" name="essay-category">
						<?php foreach($this->categoryList as $category): ?>
						<option 
						value="<?php echo $category['essaycategory_id']; ?>"
						<?php if($this->editMode == TRUE): ?>
							<?php if($category['essaycategory_id'] == $this->selectedCategory): ?>
							selected="true"
							<?php endif;?>
						<?php endif; ?>
						>
						<?php echo $category['title']; ?>
						</option>
						<?php endforeach;?>
					</select>
				</td>
            </tr>
            <tr>
                <td><label>Description</label></td>
                <td>&#58;</td>
                <td><?php echo $this->form->photoessay_description; ?></td>
            </tr>
        </tbody>
    </table>
	
	<div class="imageContainer"></div>

    <input id="submitBtn" class="btn radius" type="submit" value="Save"/>
</fieldset>
</form>