<form method="post" action="<?php echo $this->currentUrl();?>" id="photoessayForm" name="photoessayForm">
<fieldset class="wide">
<legend>Photo Essay Information</legend>
    <table>
        <tbody>
            <?php if($this->showFile == TRUE): ?>
            <tr>
                <td></td>
                <td></td>
                <td><label>Image File</label></td>
            </tr>
			<tr>
                <td></td>
                <td></td>
                <td>
					<?php echo $this->form->image_file; ?>
				</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
	            <td style="width: 400px;">
	                <span class="space_r"><?php echo $this->form->HeaderImage; ?></span>
	                <span><input alt="#TB_inline?height=300&width=400&inlineId=imageUploadDialog&modal=true" title="Upload Image" class="thickbox btn radius" type="button" value="Upload" /></span>
					<span class="tip">(933px * 450px recommended)</span>
	            </td>
        	</tr>
			<?php endif; ?>
            <tr>
                <td></td>
                <td></td>
                <td><label>Description</label></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td><?php echo $this->form->image_description; ?></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td><label>Weight (enter integer starting from 0)</label></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>
					<?php echo $this->form->image_weight; ?>
				</td>
            </tr>
		</tbody>
    </table>
	
	<div class="imageContainer"></div>

    <input id="submitBtn" class="btn radius" type="submit" value="Save"/>
</fieldset>
</form>

<?php echo $this->render('partial/upload-image-dialog.phtml');?>