<?php $this->placeholder('styles')->captureStart(); ?>
<link href="<?php echo $this->scriptUrl('/styles/table-css.php'); ?>" rel="stylesheet" type="text/css" />
<?php $this->placeholder('styles')->captureEnd(); ?>

<!-- print out any message from create/saved page proccess-->
<?php 
    if (!empty($this->message)) {
        foreach ($this->message as $warn) echo $this->flashMessage($warn);
    }
?>

<h2><?php echo $this->title; ?></h2>
<h3 class="wide">Create, Update, or Delete from the list</h3>
<div class="table-container">
    <input type="button" class="btn radius" style="margin-bottom:10px;" 
	value="+ Add Image" onclick="window.location='<?php echo $this->rootUrl('admin/photoessay/add-image/essay/'.$this->essayID) ?>'"/>
    <br class="clearfloat"  />
    
    <!-- generating alert on filter selected -->
    <br class="clearfloat" />
    <?php if (!empty($this->alert)) : ?>
        <div class="tip"> Current filter selected: <?php echo $this->alert; ?>
        </div>
    <?php endif; ?> 
    
    <br class="clearfloat"  />
    <br class="clearfloat"  />
    <table style="width:100%;" cellspacing="0">
	
		<thead>
			<tr>
		    	<th width="50%" align="center">File Name</th>
		        <th width="50%" align="center">Action</th>
		    </tr>
		</thead>

		<tbody>
		<?php if(sizeof($this->imageList) > 0): ?>
		<?php foreach($this->imageList as $data): ?>
			<tr>
				<td>
			        <a href="<?php echo $this->rootUrl(); ?>/admin/photoessay/edit-image/id/<?php echo $data['image_id']; ?>">
					<?php echo $data['file']; ?>
					</a>
			    </td>
			
			    <td>
			        <table class="cleartable">
			            <tr>
			                <td>
			                    <table class="cleartable">
			                        <tr>
			                            <td>
			                                <a class="general-remove" style="width: 100% !important;" href="<?php echo $this->rootUrl(); ?>/admin/photoessay/edit-image/id/<?php echo $data['image_id']; ?>">
											Edit Description
											</a>
			                            </td>
			                            <td>
			                                <a onclick="deletePhotoessay(<?php echo $data['image_id']; ?>);" class="general-remove" style="width: 100% !important;" href="#delete-image">
											Delete
											</a>
			                            </td>
			                        </tr>
			                    </table>
			                </td>
			            </tr>
			        </table>
			    </td>
			
			</tr>
		<?php endforeach; ?>
		<?php endif;?>
		</tbody>
	</table>

    <br class="clearfloat"  />
</div>
<div id="processLoader" class="hidden">
   <img src='<?php echo $this->imageUrl('ajax-loader-big.gif'); ?>'/>
</div>
<?php $this->placeholder('jsInline')->captureStart();?>

<script type="text/javascript">

    function deletePhotoessay(essayid)
    {
        if(confirm('Are you sure you want to delete this image?'))
        {
            tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
            $.ajax({
                type: "POST",
                url: "<?php echo $this->rootUrl().'/admin/ajax/deleteessayimage'; ?>",
                data: {'imageid' : essayid},
                success: function(data){
                    window.location.reload(true);
                },
                error: function(){alert('Error Occured, please report this to the developer');}
            });
        }
    }
    function hideAllFilter()
    {
        $('.area-box').hide();
        $('.title-box').hide();
    }
    
    function filterSwitch(value)
    {   
                
        switch(value)
        {
		    case "0": hideAllFilter();
		    		  break;
            case "1": hideAllFilter();
                      $('.title-box').fadeIn('slow');
                      $('.filter-btn').fadeIn('slow');
                      break;
        }
    }
    
    $(function(){
        $('.filter-panel').show();
    });
</script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>