<tr>
	<td>
        <a href="<?php echo $this->rootUrl(); ?>/admin/photoessay/edit/id/<?php echo $this->photoessay_id; ?>">
		<?php echo $this->title; ?></a>
    </td>

    <td>
        <table class="cleartable">
            <tr>
                <td>
                    <table class="cleartable">
                        <tr>
                            <td>
                                <a class="general-remove" style="width: 100% !important;" href="<?php echo $this->rootUrl(); ?>/admin/photoessay/edit/id/<?php echo $this->photoessay_id; ?>">
								Edit
								</a>
                            </td>
                            <td>
                                <a class="general-remove" style="width: 100% !important;" href="<?php echo $this->rootUrl(); ?>/admin/photoessay/image/id/<?php echo $this->photoessay_id; ?>">
								Add Pictures
								</a>
                            </td>
                            <td>
                                <div class="general-remove">
								<a href="#delete" onclick="deletePhotoessay(<?php echo $this->photoessay_id; ?>);">Delete</a>
								</div>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </td>
</tr>