<!-- style css untuk halaman admin -->
<?php $this->placeholder('styles')->captureStart(); ?>
    <link href="<?php echo $this->scriptUrl('/styles/table-css.php'); ?>" 
          rel="stylesheet" type="text/css" />
<?php $this->placeholder('styles')->captureEnd(); ?>

<!-- print out any message from create/saved page proccess -->
<?php 
    if (!empty($this->message)) {
        foreach ($this->message as $warn) echo $this->flashMessage($warn);
    }
?>

<!-- set page context -->
<h2>Review Menu</h2>
<h3 class="wide">Update or Delete from the list</h3>

<div class="table-container">
    <!-- generating the filter panel and row show per page filter -->
    <?php echo $this->partial('review/filter-panel.phtml'); ?>
    <?php echo $this->render('partial/page-filter.phtml'); ?>
    
    <!-- generating alert on filter selected -->
    <br class="clearfloat" />
    <?php if (!empty($this->alert)) : ?>
        <div class="tip"> Current filter selected: <?php echo $this->alert; ?>
        </div>
    <?php endif; ?> 
    
    <!-- if the paginator is not empty then print out the data -->
    <br class="clearfloat" />
    <?php if (count($this->paginator) > 0) : ?>
    
        <!-- print out the pagination control at the top of the table-->
        <?php echo $this->paginationControl($this->paginator, 'Sliding',
                                    'partial/pagination-control.phtml'); ?>
        
        <br class="clearfloat" />
        <table style="width: 100%;" cellspacing="0">
            
            <?php echo $this->partial('review/table-header.phtml') . "\n"; ?>
            <tbody>
                <?php $row_index = 0; ?>
                <?php echo $this->partialLoop('review/table-row.phtml', 
                                                $this->paginator) . "\n"; ?>
            </tbody>
        </table>
        
        <!-- print out the pagination control at the bottom of the table -->
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 
                                    'partial/pagination-control.phtml'); ?>
        
        <br class="clearfloat" />
    <?php endif; ?>	
</div>

<div id="processLoader" class="hidden">
    <img src='<?php echo $this->imageUrl('ajax-loader-big.gif'); ?>'/>
</div>

<!-- start capturing the javascript -->
<?php
    $this->placeholder('jsInline')->captureStart();
?>
<script type="text/javascript">
    /**
     * IS: -
     * FS: Semua filter box tidak tertampil
     * Desc: Menyembunyikan seluruh filter
     */
    function hideAllFilter()
    {
        $('.title-box').hide();
        $('.status-box').hide();
    }
    
    /**
     * IS: Tertampil hanya filter default 'Show All'
     * FS: Tertampil filter box tambahan sesuai pilihan
     * Desc: Mengganti tampilan filter
     */
    function filterSwitch(value)
    {   
        switch(value)
        {
            case "0": hideAllFilter();
                      break;
            case "1": hideAllFilter();
                      $('.title-box').fadeIn('slow');
                      break;
            case "2": hideAllFilter();
                      $('.status-box').fadeIn('slow');
                      break;
        }
    }
    
    /**
     * IS: Review ada
     * FS: Review tidak ada, dan dihapus dari basis data
     * Desc: Menghapus review, 
     *       send request via ajax for deleting the review from the table
     */
    function deleteReview(review_id, obj)
    {
        if (confirm('Do you really want to delete this review?'))
        {
            tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
            $.ajax(
            {
                type: "POST",
                url: "<?php echo $this->rootUrl().'/admin/ajax/deletereview'; ?>",
                data: {reviewId:review_id}, 
                success: function(data)
                {
                    obj.parents('tr.tableReviewData').remove(); 
                    window.location.reload(true);
                },
                error: function()
                {
                    alert('Error occured, please report this to the developer');
                }
            });    
        }        
    }
    
    /**
     * IS: Status review shown atau not shown
     * FS: Status review berubah dari shown menjadi not shown atau sebaliknya
     * Desc: Mengganti status review menjadi shown atau not shown
     */
    function changeReviewStatus(review_id, obj)
    {
        if (confirm('Do you really want to change this review status?'))
        {
            tb_show("", 
            "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", 
            "");
            $.ajax(
            {
                type: "POST",
                url: 
                "<?php echo $this->rootUrl().'/admin/ajax/hideshowreview'; ?>",
                data: {reviewId:review_id}, 
                success: function(data)
                {
                    obj.html(data);
                    tb_remove();
                    window.location.reload(true);
                },
                error: function()
                {
                    alert('Error occured, please report this to the developer');
                }
            });
        }        
    }
    
    $(function()
    {
        $('.filter-panel').show();
    });
</script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>