<?php 
    $this->placeholder('jsInline')->captureStart();
    echo $this->render('partial/tinyMCE.phtml');
?>
<script type="text/javascript">
    tinyMCE.execCommand('mceAddControl', false, 'reviewContent');
    
    $(function() {
        $('#submit-btn').removeAttr('disabled');
        
        $("input[type*='text']").focus(function() {
            $(this).css('border','2px solid #1E385D');
        });
        
        $("input[type*='text']").blur(function() {
            $(this).css('border','none');
        });
        
        $('#submit-btn').click(function() {
            var content = tinyMCE.activeEditor.getContent();
            $('#reviewContent').val(content);
        });
        
        $("#reviewForm").validate(
        {
            rules : 
            {
                reviewTitle:      { required :true,
                                    maxlength:100 },
                reviewContent:    { required :true },
            },
            messages : 
            {
                reviewTitle:      { required :"Review title cannot be empty!",
                                    maxlength:"Review title cannot be longer than 100 character!" },
                reviewContent:    "Review content cannot be empty!",
            }
        });
    });
</script>

<?php $this->placeholder('jsInline')->captureEnd(); ?>