    <p style="padding-left: 5px;">Stay updated with news, events and destinations at <a href="<?php echo $this->rootUrl(); ?>">indonesia.travel</a></p>
    <br />
    <ul>
        <li><img src="<?php echo $this->imageUrl('/mini-rss.png'); ?>"/>&nbsp;<a href="http://feeds.feedburner.com/IndonesiaTravelEvents">Subscribe to Events articles (RSS) </a></li>
        <li><img src="<?php echo $this->imageUrl('/mini-rss.png'); ?>"/>&nbsp;<a href="http://feeds.feedburner.com/IndonesiaTravelNews">Subscribe to News articles (RSS) </a></li>
        <li><img src="<?php echo $this->imageUrl('/mini-rss.png'); ?>"/>&nbsp;<a href="http://feeds.feedburner.com/IndonesiaTravelDestinations">Subscribe to Destinations (RSS) </a></li>
    </ul>