<tr>
	<td>
        <a href="<?php echo $this->rootUrl(); ?>/admin/regionindo/edit/id/<?php echo $this->area_id; ?>/lang/2"><?php echo $this->name; ?></a>
    </td>
    <td><?php echo $this->pointY.' , '.$this->pointX; ?></td>
    <td>
        <a class="general-remove" href="<?php echo $this->rootUrl(); ?>/admin/regionindo/edit/id/<?php echo $this->area_id; ?>/lang/2">Edit</a>
    </td>

    <td>
        <table class="cleartable">
            <tr>
                <td><a>English Translation</a></td>
            </tr>
            <tr>
                <td>
                    <table class="cleartable tiny">
                        <tr>
                            <td>
                                <a class="general-remove" href="<?php echo $this->rootUrl(); ?>/admin/regionindo/edit/id/<?php echo $this->area_id; ?>/lang/1"><?php $this->CheckRegionalIndo($this->area_id, 1)?></a>
                            </td>
                            <?php $indtrans = $this->CheckRegionalIndoTrans($this->area_id, 1);
                                  if($indtrans == true){?>
                            <td>
                                <div class="general-remove" onclick="deleteAreaEnglish(<?php echo $this->area_id;?>);">Delete</div>
                            </td><?php } ?>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </td>

    <td class="tableMiniMenu">
        <div class="general-remove" onclick="deleteArea(<?php echo $this->area_id;?>);">Delete</div>
    </td>
</tr>