<!-- PAGE-TITLE begins here -->
<div class="row-fluid section-title" style="border-left-color: #ffcc00">
    <div class="pull-left">
        <h1 style="font-size: 28px;"><?php echo $this->category['name']; ?></h1>
    </div>
    <div class="pull-right">
        <?php echo $this->paginationControl($this->paginator, 'sliding', 'shared/paginator.phtml'); ?>
    </div>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array(), ($this->langId == 1) ? "beranda" : "home"); ?>"><?php echo ($this->langId == 1) ? "Beranda" : "Home"; ?></a></li>
    <li><a href="<?php echo $this->url(array(), (($this->langId == 1) ? 'kebudayaan' : 'culture')); ?>"><?php echo $this->langId == 1 ? "Kebudayaan" : "Culture" ?></a></li>
    <li><a href="<?php
        echo $this->url(array(
            'id' => $this->category['parent_id'],
            'slug' => $this->makeUrlFormat($this->category['parent_name'])
                ), (($this->langId == 1) ? 'kategori' : 'category'));
        ?>"><?php echo $this->category['parent_name']; ?></a></li>
    <li class="active"><?php echo $this->category['name']; ?></li>
</ul>

<div class="row-fluid" id="news-page">
    <div class="span24">
        <?php
        $j = 0;
        $colors = array("#ea0000", "#ffcc00", "#33d800", "#00baff", "#ff9600");
        shuffle($colors);
        ?>
        <?php foreach ($this->culture_chunk as $index => $cultures): ?>
            <div class="row-fluid">
                <?php foreach ($cultures as $i => $culture): ?>
                    <?php
                    $url = $this->url(array(
                        'destId' => $culture['poi_id'],
                        'slug' => $this->makeUrlFormat($culture['poiName'])
                            ), ($this->langId == 1 ? 'detail-kebudayaan' : 'culture-detail'));
                    $filename = IMAGE_FOLDER . '/upload/culture/' . $culture['source'];
                    ?>
                    <div class="span12 article-wrapper">
                        <div class="row-fluid">
                            <?php if (is_file($filename)): ?>
                                <div class="span7">
                                    <img src="<?php echo $this->timthumb($culture['source'], 150, 220); ?>" 
                                         alt="<?php echo $culture['poiName']; ?>"/>
                                </div>
                            <?php endif; ?>
                            <div class="<?php echo is_file($filename) ? 'span16 offset1' : 'span24'; ?>">
                                <div class="limit" style="height: 220px; word-wrap: break-word;">
                                    <h2 class="article-title" style="background: <?php echo $colors[$j % 5]; ?>">
                                        <a href="<?php echo $url; ?>">
                                            <?php echo $culture['poiName']; ?>
                                        </a>
                                    </h2>
                                    <p><?php echo $this->truncate($this->htmlDecode($culture['description']), 160); ?></p>
                                </div>
                                <!--                                <a class="s-btn s-btn-with-icon pull-right" 
                                                                   href="<?php echo $url; ?>">
                                                                    <span class="rulycon-arrow-right-2"></span> 
                                <?php $readMore = ($this->languageId == 1) ? "Selengkapnya" : "Read more"; ?>
                                <?php echo $readMore; ?>
                                                                </a>-->
                            </div>
                        </div>
                    </div>
                    <?php $j++; ?>
                <?php endforeach; ?>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<dir class="row-fluid section-title" style="padding-bottom: 15px;">
    <div class="pull-right">
        <?php echo $this->paginationControl($this->paginator, 'sliding', 'shared/paginator.phtml'); ?>
    </div>
</dir>