<div class="row-fluid">
  <form action="" method="post" class="" enctype="multipart/form-data">
    <div class="control-group">
      <label for="name" class="control-label">Name</label>
      <div class="controls">
        <?php echo $this->form->name ?>
      </div>
    </div>

    <div class="control-group">
      <label for="description" class="control-label">Description</label>
      <div class="controls">
        <?php echo $this->form->description ?>
      </div>
    </div>

    <div class="control-group">
      <div class="controls">
        <?php echo $this->form->submit ?>
      </div>
    </div>
  </form>
</div>
<?php echo $this->render('partial/tinyMCE.phtml'); ?>