<?php foreach ($this->messages as $index => $message): ?>
    <div class="alert alert-success">
        <a href="#" data-dismiss="alert" class="close">x</a>
        <strong><?php echo $message; ?></strong>
    </div>
<?php endforeach; ?>

<form action="" method="post">
    <?php echo $this->render('partial/pageFilter.phtml'); ?>

    <div class="row-fluid">
        <table class="table table-striped table-hover" id="tabel-culture">
            <col width="1%"/>
            <col width="7%"/>
            <col width="20%"/>
            <col width="10%"/>
            <col width="10%"/>
            <col width="10%"/>
            <col width="28%"/>
            <col width="5%"/>
            <col width="6%"/>
            <col width="6%"/>
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" onclick="
                                var checkboxes = $('#tabel-culture tbody input:checkbox');
                                if ($(this).attr('checked'))
                                    $(checkboxes).attr('checked', true);
                                else
                                    $(checkboxes).removeAttr('checked');"/>
                    </th>
                    <th colspan="2">
                        <button name="filter[sort]" value="name">
                            Nama Kebudayaan        
                            <?php if ($this->filter['sort'] == 'name'): ?>
                                <?php if ($this->filter['order'] == 'ASC'): ?>
                                    <span class="rulycon-arrow-up-2"></span>
                                <?php elseif ($this->filter['order'] == 'DESC'): ?>
                                    <span class="rulycon-arrow-down-2"></span>
                                <?php endif; ?>
                            <?php endif; ?>
                        </button>
                    </th>
                    <th>Status</th>
                    <th>Kategori</th>
                    <th>Area</th>
                    <th>
                        <button name="filter[sort]" value="created_at">
                            Tanggal
                            <?php if ($this->filter['sort'] == 'created_at'): ?>
                                <?php if ($this->filter['order'] == 'ASC'): ?>
                                    <span class="rulycon-arrow-up-2"></span>
                                <?php elseif ($this->filter['order'] == 'DESC'): ?>
                                    <span class="rulycon-arrow-down-2"></span>
                                <?php endif; ?>
                            <?php endif; ?>
                        </button>
                    </th>
                    <th>
                        <button name="filter[sort]" value="viewer">
                            <span class="rulycon-eye"></span>
                            <?php if ($this->filter['sort'] == 'viewer'): ?>
                                <?php if ($this->filter['order'] == 'ASC'): ?>
                                    <span class="rulycon-arrow-up-2"></span>
                                <?php elseif ($this->filter['order'] == 'DESC'): ?>
                                    <span class="rulycon-arrow-down-2"></span>
                                <?php endif; ?>
                            <?php endif; ?>
                        </button>
                    </th>
                    <th>EN</th>
                    <th></th>
                </tr>
                <tr>
                    <th></th>
                    <th colspan="2">
                        <?php
                        echo $this->formText('filter[name]', $this->filter['name'], array(
                            'placeholder' => 'Ketikan nama kebudayaan untuk pencarian...'
                        ));
                        ?>
                    </th>
                    <th>
                        <?php
                        $selectStatus = array(
                            null => 'Tampilkan semua',
                            0 => "Diarspikan ({$this->statusesCount['archived']})",
                            1 => "Draft ({$this->statusesCount['draft']})",
                            2 => "Menunggu Persetujuan ({$this->statusesCount['pending']})",
                            3 => "Diterbitkan ({$this->statusesCount['publish']})",
                            4 => "Featured ({$this->statusesCount['featured']})"
                        );
                        echo $this->formSelect('filter[status]', $this->filter['status']
                                , array('class' => 'span12'), $selectStatus);
                        ?>
                    </th>
                    <th>
                        <?php
                        echo $this->formSelect('filter[main_category]', $this->filter['main_category']
                                , array('class' => 'span12'), $this->categories);
                        ?>
                    </th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $index => $culture): ?>
                    <tr <?php echo ((bool) $culture->featured) ? "title='Tampil secara acak di halaman depan'" : ""; ?>>
                        <td class="text-center">
                            <input type="checkbox" name="cultures[]" value="<?php echo $culture->poi_id; ?>"/>
                        </td>
                        <td>
                            <?php
                            $src = 'default.jpg';
                            $w = 50;
                            $h = 50;
                            $q = 100;
                            if (is_file(UPLOAD_FOLDER . 'culture/' . $culture->image)) {
                                $src = 'upload/culture/' . $culture->image;
                            }
                            $timthumb = $this->
                                    imageUrl("timthumb.php?src={$src}&w={$w}&h={$h}&q={$q}");
                            ?>

                            <img class="thumbnail" src="<?php echo $timthumb; ?>" 
                                 title="<?php echo $culture->image; ?>" alt=""/>
                        </td>
                        <td>
                            <a target="_blank" 
                               href="<?php
                               echo $this->url(array(
                                   'destId' => $culture->poi_id,
                                   'slug' => $this->makeUrlFormat($culture['name'])
                                       ), 'detail-kebudayaan');
                               ?>">
                                   <?php echo $culture->name; ?>
                            </a>
                        </td>
                        <td>
                            <?php switch ($culture->status): case 0: ?>
                                    <span class='text muted'>Diarspikan</span>
                                    <?php break; ?>
                                <?php case 1; ?>
                                    <span class='text muted'>Draft</span>
                                    <?php break; ?>
                                <?php case 2; ?>
                                    <span class='text text-warning'>Menunggu Persetujuan</span>
                                    <?php if ($this->userInfo->canApprove): ?>
                                        <?php $approve_url = $this->url(array('action' => 'approve', 'id' => $culture->poi_id)); ?>
                                        <br />
                                        <a href='<?php echo $approve_url; ?>' class='btn'>Disetujui</a>
                                    <?php endif; ?>
                                    <?php break; ?>
                                <?php case 3; ?>
                                    <span class='text text-success'>Diterbitkan</span>
                                    <?php break; ?>
                            <?php endswitch; ?>
                            <?php if ((bool) $culture->featured): ?>
                                <div class="label label-info">Featured</div>
                            <?php endif; ?>
                        </td>
                        <td><?php echo $culture->main_category; ?></td>
                        <td><?php echo $culture->area; ?></td>
                        <td>
                            <small>
                                <div>
                                    Dibuat:
                                    <strong>
                                        <?php echo strftime("%e %B %Y", strtotime($culture->created_at)); ?>
                                        <small><?php echo date('H:i', strtotime($culture->created_at)); ?></small>
                                    </strong>
                                    oleh      
                                    <strong><?php echo ucfirst($culture->created_by); ?></strong>
                                </div>
                                <?php if (null != ($culture->approved_at)): ?>
                                    <div>
                                        Disetujui:       
                                        <strong>
                                            <?php echo strftime("%e %B %Y", strtotime($culture->approved_at)) ?>
                                            <small><?php echo date('H:i', strtotime($culture->approved_at)); ?></small>
                                        </strong>
                                        oleh 
                                        <strong><?php echo ucfirst($culture->approved_by); ?></strong>
                                    </div>
                                <?php endif; ?>

                                <?php if (null != $culture->updated_at): ?>
                                    <div>
                                        Disunting:      
                                        <strong>
                                            <?php echo strftime("%e %B %Y", strtotime($culture->updated_at)) ?>
                                            <small><?php echo date('H:i', strtotime($culture->updated_at)); ?></small>
                                        </strong>
                                        oleh 
                                        <strong><?php echo ucfirst($culture->updated_by); ?></strong>
                                    </div>
                                <?php endif; ?>
                            </small>
                        </td>
                        <td>
                            <span class="badge badge-info"><?php echo $culture->viewer; ?></span>
                        </td>
                        <td class="text-center">
                            <?php if ($culture->isTranslated): ?>
                                <a href="<?php echo $this->url(array('action' => 'edittranslation', 'id' => $culture->poi_id)); ?>" title="Sunting Translasi">
                                    <span class="rulycon-pencil"></span>
                                </a>
                                <a target="_blank" 
                                   href="<?php
                                   echo $this->url(array(
                                       'destId' => $culture->poi_id,
                                       'slug' => $this->makeUrlFormat($culture->name)
                                           ), 'culture-detail');
                                   ?>" 
                                   title="Pratinjau Translasi">
                                    <span class="rulycon-eye-2"></span>
                                </a>

                                <a href=" <?php echo $this->url(array('action' => 'deletetranslation', 'id' => $culture->poi_id)); ?>"
                                   title="Hapus Translasi"   
                                   onclick="if (!confirm('Apakah anda yakin ingin' + ' menghapus translasi ini?'))
                                                       return false">
                                    <span class="rulycon-remove-2"></span>
                                </a>
    <?php else: ?>
                                <a href="<?php echo $this->url(array('action' => 'translate', 'id' => $culture->poi_id)); ?>" 
                                   title="Buat Translasi">
                                    <span class="rulycon-pencil-2"></span>
                                </a>
    <?php endif; ?>
                        </td>
                        <td class="text-center">
                            <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $culture->poi_id, 'lang' => 1)); ?>"
                               title="Sunting">
                                <span class="rulycon-pencil"></span>
                            </a>

                            <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $culture->poi_id)); ?>"
                               title="Hapus"     
                               onclick="if (!confirm('Apakah anda ingin ' + 'menghapus item ini?'))
                                               return false">
                                <span class="rulycon-remove"></span>
                            </a>
                        </td>
                    </tr>
<?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
</form>