<div class="filter-panel hidden">
    
    <h4 style="margin-top: 10px;"><label for="filterPage">Filter:</label></h4>
    
    <form action="<?php echo $this->currentUrl(); ?>" method="post">
        <select class="filter-box" name="filterPage" id="filterPage"
                onchange="filterSwitch(this.value);">
            <option value="0">Show All</option>
            <option value="1">Name</option>
        </select>
        
        <input type="text" class="title-box mediumele hidden" 
               name="filterTitle"/>
        
        <input type="submit" value="Go" class="btn radius" />
    </form>                    
</div>