<?php $this->placeholder('jsInline')->captureStart();?>
<?php
    echo $this->render('partial/tinyMCE.phtml');
    /*Put all your Javascript function below*/
?>
<script type="text/javascript">
tinyMCE.execCommand('mceAddControl', false, 'packDescription');

$(function(){
   $("#tourpackageForm").validate({
        rules : {
                   packTitle: "required",
                   packContact: "required",
                   packWebsite: {required:true,url:true}
                },
        messages : {
                     packTitle : "Please enter a name!",
                     packContact : "Please enter a contact information",
                     packWebsite : {required:"Please enter the website URL!",url:"Please enter a valid URL, make sure to use the Http:// prefix[dot]com"}
                   }
    });
        
});
</script>
<?php $this->placeholder('jsInline')->captureEnd();?>