<tr>
    <td>
        <table class="cleartable">
            <tr>
                <td>
                    <a href="<?php echo $this->rootUrl(); ?>/admin/tourpackageindo/edit/id/<?php echo $this->package_id; ?>/lang/2"><?php echo $this->title; ?></a>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="cleartable tiny">
                        <tr>
                            <td>
                                <a class="general-remove" href="<?php echo $this->rootUrl(); ?>/admin/tourpackageindo/edit/id/<?php echo $this->package_id; ?>/lang/2">Edit</a>
                            </td>
                            <td>
                                <div class="general-remove" onclick="deletePackage(<?php echo $this->package_id; ?>);">Delete</div>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </td>
    <td>
        <?php if($this->contact != ''): ?>
            <?php echo $this->contact; ?>
        <?php else:?>
            not available
        <?php endif; ?>
    </td>
    <td style="w">
        <?php if($this->website != ''): ?>
            <?php echo wordwrap($this->website,20,"<br />\n",TRUE); ?>
        <?php else:?>
            not available
        <?php endif; ?>
    </td>

    <td>
        <table class="cleartable">
            <tr>
                <td>
                    <a>English Translation</a>
                </td>
            </tr>
            <tr>
                <td>
                    <table class="cleartable tiny">
                        <tr>
                            <td>
                                <a class="general-remove" href="<?php echo $this->rootUrl(); ?>/admin/tourpackageindo/edit/id/<?php echo $this->package_id; ?>/lang/1"><?php $this->CheckPackageIndo($this->package_id, 1)?></a>
                            </td>
                            <?php $indtrans = $this->CheckPackageIndoTrans($this->package_id, 1);
                                  if($indtrans == true){?>
                            <td>
                                <div class="general-remove" onclick="deletePackageEnglish(<?php echo $this->package_id; ?>);">Delete</div>
                            </td><?php } ?>
                        </tr>
                    </table>
                </td>
            </tr>
        </table>
    </td>

</tr>