<?php $this->placeholder('styles')->captureStart(); ?>
<link href="<?php echo $this->scriptUrl('/styles/table-css.php'); ?>" rel="stylesheet" type="text/css" />
<?php $this->placeholder('styles')->captureEnd(); ?>

<!-- print out any message from create/saved page proccess-->
<?php 
    if (!empty($this->message)) {
        foreach ($this->message as $warn) echo $this->flashMessage($warn);
    }
?>

<h2>Promotion Materials Menu</h2>
<h3 class="wide">Create, Update, or Delete from the list</h3>
<div class="table-container">
    <input type="button" class="btn radius" style="margin-bottom:10px;" 
           value="+ Add Promotion Material" 
           onclick="window.location='<?php echo $this->rootUrl('admin/materialpromotion/create'); ?>'"/>
    <br class="clearfloat"  />
    <?php echo $this->partial('materialpromotion/filter-panel.phtml')."\n"; ?>
    <?php echo $this->render('partial/page-filter.phtml'); ?>

    <!-- generating alert on filter selected -->
    <br class="clearfloat" />
    <?php if (!empty($this->alert)) : ?>
        <div class="tip"> Current filter selected: <?php echo $this->alert; ?>
        </div>
    <?php endif; ?> 
    
    <br class="clearfloat"  />
    <?php if(count($this->paginator)>0) :?>
        <?php echo $this->paginationControl($this->paginator,'Sliding','partial/pagination-control.phtml'); ?>

    <table style="width:100%;" cellspacing="0">
            <?php echo $this->partial('materialpromotion/table-header.phtml')."\n"; ?>
        <tbody>
                <?php $row_index = 0; ?>
                <?php echo $this->partialLoop('materialpromotion/table-row.phtml',$this->paginator)."\n"; ?>
        </tbody>
    </table>

        <?php echo $this->paginationControl($this->paginator,'Sliding','partial/pagination-control.phtml'); ?>
    <br class="clearfloat"  />
    <?php endif; ?>
    <br class="clearfloat"  />
</div>

<div id="processLoader" class="hidden">
    <img src='<?php echo $this->imageUrl('ajax-loader-big.gif'); ?>'/>
</div>

<?php 
$this->placeholder('jsInline')->captureStart();
?>
<script type="text/javascript">
    function deleteMaterial(material_id)
    {
        if(confirm('Are you sure you want to delete this promotional material?'))
        {
            tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
            $.ajax({
                type: "POST",
                url: "<?php echo $this->rootUrl('/admin/ajax/deletematerial'); ?>",
                data: {material_id:material_id},
                success: function(data){
                    window.location.reload(true);
                },
                error: function(){alert('Error Occured, please report this to the developer');}
            });        
        }
    }

    function hideAllFilter()
    {
        $('.title-box').hide();
    }

    function filterSwitch(value)
    {
        switch(value)
        {
            case "0": hideAllFilter();
                break;
            case "1": hideAllFilter();
                $('.title-box').fadeIn('slow');
                break;
        }
    }
    
    $(function(){
        $('.filter-panel').show();
    });
</script> 
<?php $this->placeholder('jsInline')->captureEnd(); ?>