<div class="filter-panel">
    
    <form action="<?php echo $this->currentUrl(); ?>" method="post" class="form-inline well">
      <label for="filterPage" class="control-label">Show Comment On</label>
        <select class="filter-box" name="filterPage" id="filterPage" 
                onchange="filterSwitch(this.value);">
            <?php 
                /** Option filter */
                $option = array(
                    '1' => 'News',
                    '2' => 'Event',
                    '3' => 'Review',
                );
                /** Menulis option dropdown list */
                foreach ($option as $filter => $filter_name) {
                    $selected = ($filter == $this->filter) ? ' selected' : '';
                    echo "<option value='" . $filter . "'" . $selected . ">" . $filter_name . "</option>";
                }
            ?>
        </select>
        
        <input type="submit" value="Go" class="btn radius"/>
    </form>
</div>