<link rel="stylesheet" href="<?php echo $this->scriptUrl('/lib/bootstrap/css/bootstrap.min.css') ?>" />
<link rel="stylesheet" href="<?php echo $this->scriptUrl('/lib/bootstrap/css/bootstrap-responsive.min.css') ?>" />
<link rel="stylesheet" href="<?php echo $this->scriptUrl('/lib/plupload/js/jquery.plupload.queue/css/plupload-gebo.css') ?>" />


<div class="row-fluid">
  <div class="span12">
    <div id="multi_upload" class="gebo-upload"></div>
  </div>
</div>



<div class="row-fluid">
  <div class="row-fluid">
    <div class="span12">
      <ul class="thumbnails">
        <?php foreach ($this->paginator as $index => $image): ?>
          <?php
          $src = "upload/{$this->folder}/{$image}";
          $w = 100;
          $h = 100;
          $q = 100;
          $timthumb = $this->imageUrl
                  ("timthumb.php?src={$src}&w={$w}&h={$h}&q={$q}");
          ?>
          <li>
            <img src="<?php echo $timthumb; ?>"
                 alt=""
                 class="thumbnail"
                 title="<?php echo $image; ?>"
                 data="<?php echo $this->imageUrl($src); ?>"
                 style="cursor: pointer"
                 onclick="FileBrowserDialogue.mySubmit($(this))"/>
          </li>
        <?php endforeach; ?>
      </ul>
    </div>
  </div>

  <div class="row-fluid">
    <div class="span12"
         style="padding-right: 20px;padding-left: 20px">
      <span class="text text-info pull-left">
        Klik pada gambar untuk memasukannya pada editor.
      </span>
      <?php
      echo $this->paginationControl($this->paginator, 'sliding',
              'partial/pagination_control.phtml');
      ?>
    </div>
  </div>
</div>

<script type="text/javascript" src="<?php echo $this->scriptUrl('/lib/jquery/jquery.min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->scriptUrl('/lib/tiny_mce/tiny_mce_popup.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->scriptUrl('/lib/tiny_mce/tiny_mce.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->scriptUrl('/lib/plupload/js/plupload.full.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->scriptUrl('/lib/plupload/js/jquery.plupload.queue/jquery.plupload.queue.full.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->scriptUrl('/lib/plupload/js/i18n/id.js'); ?>"></script>
<script type="text/javascript">
  
  $(function() {
    
    $("#multi_upload").pluploadQueue({
      // General settings
      runtimes : 'html5,flash,silverlight',
      url : '<?php echo $this->url() ?>',
      max_file_size : '10mb',
      chunk_size : '1mb',
      unique_names : true,
      browse_button : 'pickfiles',
      language: 'id',
        
      // Specify what files to browse for 
      filters : [
        {title : "Image files", extensions : "jpg,png"},
      ],
        
      // Flash settings
      flash_swf_url : 'lib/plupload/js/plupload.flash.swf',
        
      // Silverlight settings
      silverlight_xap_url : 'lib/plupload/js/plupload.silverlight.xap'
    });
    
    var uploader = $('#multi_upload').pluploadQueue();

    uploader.bind('FileUploaded', function() {
      if (uploader.files.length == (uploader.total.uploaded + uploader.total.failed)) {
        location.reload();
      }
    });
  });
  
  

  var win = tinyMCEPopup.getWindowArg("window");
  var input = tinyMCEPopup.getWindowArg("input");
  var res = tinyMCEPopup.getWindowArg("resizable");
  var inline = tinyMCEPopup.getWindowArg("inline")

  var FileBrowserDialogue = {
    init : function () {
    },
    mySubmit : function (obj) {
      URL = obj.attr('data');
      win.document.getElementById(tinyMCEPopup.getWindowArg("input")).value = URL;
      win.ImageDialog.showPreviewImage(URL);
      tinyMCEPopup.close();
    }
  }
  tinyMCEPopup.onInit.add(FileBrowserDialogue.init, FileBrowserDialogue);
</script>