<div class="row-fluid">
  <form method="post" id="poiForm" enctype="multipart/form-data" class="" name="poiForm">
    <?php echo $this->form->SaveStatus; ?>
    <?php echo $this->form->Count_area; ?>
    <?php echo $this->form->Count_category; ?>
    <div class="row-fluid">
      <div class="control-group">
        <label for="Name" class="control-label">Nama</label>
        <div class="controls">
          <?php echo $this->form->name ?>
        </div>
      </div>

      <div class="control-group">
        <div class="controls">
          <label for="Featured" class="control-label checkbox">
            <?php echo $this->form->featured; ?>
            Cek jika kebudayaan ini ingin ditampilkan di halaman depan
          </label>
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <div class="span8">
        <div class="row-fluid">
          <div class="control-group">
            <div class="controls">
              <?php echo $this->form->description; ?>
            </div>
          </div>
        </div>

        <div class="control-group">
          <div class="controls">
            <div class="well" style="height: 350px">
              <div id="mapCMS"></div>
              <?php echo $this->form->Poi_x; ?>
              <?php echo $this->form->Poi_y; ?>
            </div>

          </div>
        </div>


        <div class="well">
          <fieldset>
            <legend class="f_legend" style="margin: 0">Gambar</legend>
            <div class="control-group">
              <div class="controls">
                <input type="button" value="+ Gambar" onclick="addImage()" class="btn" style="margin-bottom: 5px;"/>
                <table id="images" class="table table-striped table-bordered table-condensed" style="margin-left: 0;float: none;">
                  <col width="35%"/>
                  <col width="58%"/>
                  <col width="7%"/>
                  <thead>
                    <tr>
                      <th>
                        Judul
                      </th>
                      <th colspan="2">
                        Gambar <small style="font-size: 11px">(Format Gambar: image/jpeg)</small>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php if (isset($this->images)): ?>
                      <?php foreach ($this->images as $image): ?>
                        <?php
                        $link = $this->imageUrl('upload/culture/' . $image['source']);
                        ?>
                        <tr>
                          <td><input type="text" name="existingImages[<?php echo $image['gallery_id'] ?>][name]" value="<?php echo $image['name'] ?>" /></td>
                          <td><a href="<?php echo $link ?>" target="_blank"/><?php echo $image['source'] ?></a></td>
                          <td><a class="btn" onclick="deleteExistingImage($(this), <?php echo $image['gallery_id'] ?>)">Hapus</a></td>
                        </tr>
                      <div>

                      </div>
                    <?php endforeach; ?>
                  <?php endif ?>
                  </tbody>
                </table>
              </div>
            </div>
          </fieldset>
        </div>



        <div class="well">

          <fieldset>
            <legend class="f_legend" style="margin: 0">Tautan Video</legend>
            <div class="control-group">
              <div class="controls">
                <input type="button" value="+ Tautan Video" onclick="addVideoLink()" class="btn"/><br />
                <table id="videoLinks" class="table-striped table table-bordered table-condensed" style="margin-left:0; margin-top: 5px;">
                  <col width="35%"/>
                  <col width="58%"/>
                  <col width="7%"/>
                  <thead>
                    <tr>
                      <th>Judul</th>
                      <th colspan="2">Tautan YouTube<small style="font-size: 11px;">(eg. http://www.youtube.com/watch?v=3gkMvpSWxKs)</small></th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php if (isset($this->cultureVideos)): ?>
                      <?php foreach ($this->cultureVideos as $key => $video): ?>
                        <tr>
                          <td><input type="text" name="existingVideo[<?php echo $video['id'] ?>][title]" value="<?php echo $video['title'] ?>" /></td>
                          <td><a style="font-size: 11px" target="_blank" href="<?php echo $video['link'] ?>"><?php echo $video['link'] ?></a></td>
                          <td><a class="btn" onclick="deleteExistingVideo(<?php echo $video['id'] ?>, deleteVideo($(this)))">Hapus</a></td>
                        </tr>
                      <?php endforeach; ?>
                    <?php endif ?>
                  </tbody>
                </table>
              </div>

            </div>

          </fieldset>
        </div>

        <div class="well">
          <fieldset>
            <legend class="f_legend" style="margin: 0">Lampiran Berkas</legend>
            <div class="control-group">
              <div class="controls">
                <input type="button" value="+ Berkas" onclick="addFiles()" class="btn" style="margin-bottom: 5px;"/>
                <table id="files" class="table table-striped table-bordered table-condensed" style="margin-left: 0;float: none;">
                  <col width="35%"/>
                  <col width="58%"/>
                  <col width="7%"/>
                  <thead>
                    <tr>
                      <th>
                        Judul
                      </th>
                      <th colspan="2">
                        Berkas <small style="font-size: 11px">(Format Berkas: .doc, .docx, .xls, .xlsx, .pdf, .zip, ,mp3)</small>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php if (isset($this->files)): ?>
                      <?php foreach ($this->files as $file): ?>
                        <?php
                        $link_file = $this->imageUrl('upload/documents/' . $file['name']);
                        ?>
                        <tr>
                          <td><input type="text" name="existingFiles[<?php echo $file['id'] ?>][title]" value="<?php echo $file['title'] ?>" /></td>
                          <td><a href="<?php echo $link_file ?>" /><?php echo $file['name'] ?></a></td>
                          <td><a class="btn" onclick="deleteFileExisting($(this), <?php echo $file['id'] ?>)">Hapus</a></td>
                        </tr>
                      <?php endforeach; ?>
                    <?php endif; ?>
                  </tbody>
                </table>

              </div>

            </div>
          </fieldset>
        </div>

        <div class="well">
          <fieldset>
            <legend class="f_legend" style="margin: 0">Artikel Terkait</legend>
            <div class="control-group">
              <div class="controls">
                <input class="btn radius valid" type="button" onclick="relatedArticle();" value="+ Artikel Terkait" style="margin-bottom:10px;"><br />
                <input type="hidden" size=1 id="counterRelated" name="counterRelated" value="<?php echo count($this->ralated_news); ?>" />
                <input type="hidden" size=1 id="counterDel" name="counterDel" value="0" />


                <table id="tbrelated-article" class="table table-stripped table-bordered table-condensed" style="margin-left: 0">
                  <col width="35%"/>
                  <col width="58%"/>
                  <col width="7%"/>
                  <thead>
                  <th>Judul</th>
                  <th colspan="2">Tautan Artikel <small style="font-size: 11px">(eg. http://id.wikipedia.org/wiki/Angklung)</small></th>
                  </thead>
                  <tbody>
                    <?php if (sizeof($this->ralated_news)): ?>
                      <?php
                      $counter = 1;
                      ?>
                      <?php foreach ($this->ralated_news as $ralated_news): ?>
                        <tr>
                          <td>
                            <input type="text" id="relatedLabel<?php echo $ralated_news->related_id; ?>" class="valid" name="label<?php echo $counter; ?>" value="<?php echo $ralated_news->label; ?>" />
                          </td>
                          <td>
                            <input type="hidden" id="relatedLink<?php echo $ralated_news->related_id; ?>" class="valid" name="link<?php echo $counter; ?>" value="<?php echo $ralated_news->link; ?>" />
                            <a target="_blank" href="<?php echo $ralated_news->link; ?>"><?php echo $ralated_news->link; ?></a>
                          </td>
                          <td>
                            <a class="btn" id="<?php echo $ralated_news->related_id; ?>" onclick="delRelatedArticleEdit($(this));">Hapus</a>
                          </td>
                        </tr>
                        <?php $counter++; ?>
                      <?php endforeach; ?>
                    <?php endif; ?>
                  </tbody>
                </table>
                <div id="tmpDelete">
                </div>

              </div>
            </div>
          </fieldset>
        </div>
      </div>

      <div class="span4 well" >
        <div class="control-group">
          <label for="Header_image" class="control-label">Fitur Gambar</label>
          <div class="controls">
            <div class="fileupload fileupload-new" data-provides="fileupload">
              <div class="fileupload-new thumbnail" style="width: 200px; height: 150px;">
                <?php if (isset($this->header_image)): ?>
                  <img src="<?php echo $this->imageUrl("timthumb.php?src=upload/culture/{$this->header_image}&w=250&h=150&q=100") ?>" alt="" />
                <?php else: ?>
                  <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=650px+x+280px" />
                <?php endif; ?>


              </div>
              <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 200px; max-height: 150px; line-height: 20px;"></div>
              <div>
                <span class="btn btn-file"><span class="fileupload-new">Pilih Gambar</span><span class="fileupload-exists">Change</span><?php echo $this->form->header_image; ?></span>
                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Hapus</a>
              </div>
            </div>
          </div>


        </div>
        <hr />

        <div class="control-group">
          <label for="CategorySelect" class="control-label">Kategori</label>
          <div class="controls">
            <table>
              <tr>
                <td>
                  <span class="margin_r"><?php echo $this->form->Category_Select; ?></span>

                </td>
              </tr>
            </table>
          </div>
          <div class="controls">
            <table>
              <tr><td class="child-category"><?php echo $this->form->Category_Child; ?></td></tr>
              <tr><td>
                <span><input type="button" class="btn" value="Tambah" onclick="addCategory();" id="addCategoryBtn"/></span>
              </td></tr>
              <tr>
                <td><table id="categorycontainer"></table></td>
              </tr>
              <tr>
                <td><?php echo $this->form->Category_counter; ?></td>
              </tr>
              <tr>
              </td><td><?php echo $this->form->Main_category; ?></td>
          </tr>
        </table>
            
      </div>

    </div>

    <hr />


    <div class="control-group">
      <label for="IslandListOptions" class="control-label">Pilih Area</label>
      <div class="controls">
        <table>
          <tr>
            <td><?php echo $this->form->Island_Select; ?></td>
          </tr>
          <tr>
            <td class="province-list"></td>
          </tr>
          <tr>
            <td class="area-list"></td>
          </tr>
          <tr>
          <div id="areacontainer"></div>
          </tr>
          <tr>
            <td>
              <span class="space_r"><input id="addAreaBtn" class="btn radius" style="display: none;" type="button" value="Tambah Area" onclick="addArea(<?php
                if ($this->state_edit) {
                  echo $this->poi_id;
                }
                ?>);" /></span>
              <span class="rel-loader"></span>
            </td>
          </tr>
          <tr>
            <td><?php echo $this->form->Area_counter; ?></td>
          </tr>
        </table>
      </div>
    </div>
    <hr />
    <div class="control-group">
      <label for="">Kebudayaan Terkait</label>
      <div class="controls">
        <table id="relatedPoiContainer" class="table table-striped" style="margin-left: 0">
          <col width="90%"/>
          <col width="10%"/>
        </table >
        <?php echo $this->form->relPoi_counter; ?>
      </div>
    </div>
  </div>
</div>

<div class="row-fluid">
  <hr />
  <?php echo $this->form->draft ?>
  <?php echo $this->form->submit ?>
</div>
</form>
</div>


<?php echo $this->render('partial/upload-image-dialog.phtml'); ?>


<script type="text/javascript">
  function addVideoLink() {
    $error = false;
    $('#videoLinks').show();
    $('#videoLinks > tbody input').each(function(){
      $(this).rules('add',{
        required: true,
        url: $(this).attr('type') == 'url'? true : false,
        messages: {
          'required': '<br />Masukan Teks',
          'url': '<br />Masukan URL yang benar'
        }
      });
      if($(this).val() == '') $error = true
    });
    if($error) alert('Isi bagian yang kosong')
    else {
      $title = '<input type="text" name="videos[title][]" placeholder="Title" />';
      $link = '<input type="url" name="videos[link][]" placeholder="Youtube Link" />';
      $delete = '<a class="btn" onclick="deleteVideo($(this))">Delete</a>';
      $('#videoLinks > tbody').append("<tr><td>"+$title+"</td><td>"+$link+"</td><td>" + $delete +"</td></tr>");
    }
  }
                                                                                                                                                                                                                                            
  $(function() {
    updateVideoLink();
  })
                                                                                                                                                                                                                                                
  function updateVideoLink() {
    if($("#videoLinks > tbody tr").length == 0) {
      $("#videoLinks").hide();
    }
  }
                                                                                                                                                                                                                                                                                                                  
  function deleteVideo(obj) {
    $(obj).parent().parent().remove();
    updateVideoLink();
  }
                                                                                                                                                                                
  function deleteExistingVideo(id, callback){
    $.ajax({
      type: 'POST',
      url: '<?php echo $this->rootUrl() . '/admin/ajax/deleteVideoLink' ?>',
      data: 'id=' + id,
      success: callback
    });
  }
                                                                                                                                                                                                                                                                                                                  
</script>

<script type="text/javascript">
  function addFiles() {
    $error = false;
    $('table#files tbody input').each(function(){
      if($(this).val() == '') $error = true
    });
    if($error) alert('Masukan nilai')
    else {
      $title = '<input type="text" name="titles[]" placeholder="Title"/>';
      $file = '<div width="500" class="uneditable-input">' 
        + '<i class="icon-file fileupload-exists"></i><span class="fileupload-preview">'
        + '</span></div><span class="btn btn-file">'
        + '<span class="fileupload-new">Select file</span>'
        + '<input type="file" name="files[]" onchange="change($(this))">'
        + '</span><br />'
        + '<label for="files[]" generated="true" class="error" style=""></label>';
      $delete = '<a class="btn" onclick="deleteFile($(this))">Delete</a>';
                                                                                  
      $('table#files tbody').append("<tr'><td>"+$title+"</td><td>"+$file+"</td><td>"+$delete +"</td></tr>");
      $('table#files').show();
      $('table#files tbody input[type=file]').each(function(){
        $(this).rules('add',{
          required: true,
          accept: 'docx?|xls|xlsx|pdf|zip|mp3',
          messages: {}
        });
      });
      $('table#files tbody input[type=text]').each(function(){
        $(this).rules('add',{
          required: true,
          messages: {}
        });
      });
    }
                                                                                      
  }
                                                                                                                                                                                                                                                                                                                    
  function change(obj) {
    $(obj).parent()
    .siblings('div')
    .find('.fileupload-preview')
    .text($(obj).val());
  }
                                                                                                                                                                                                                                                                                                                    
  function deleteFile(obj) {
    $(obj).parent().parent().remove();
    updateFileTable();
  }
                                                                                                                                                                                                                                                                                    
  $(function() {
    updateFileTable();
  })
                                                                                                                                                                                                                                                                                        
  function updateFileTable(){
    if($("table#files tbody > tr").length == 0) {
      $('table#files').hide();
    }
  }
                                                                                                                                                                                                                                                                                                                    
  function deleteFileExisting(obj, id) {
    $.ajax({
      url: '<?php echo $this->rootUrl() . '/admin/ajax/deleteExistingFile' ?>',
      data: 'id=' + id,
      type: 'POST',
      success: function(response){
        $(obj).parent().parent().slideUp('fast').remove();
        updateFileTable();
      }
    });
  }
</script>


<script type="text/javascript">
  function addImage() {
    $error = false;
    $("table#images").show();
    $('table#images tbody input').each(function(){
      $(this).rules('add',{
        required: true,
        messages: {
          'required': '<br />Masukan Berkas',
          'file': '<br />Masukan berkas dengan format yang valid'
        }
      });
      if($(this).val() == '') $error = true
    });
    if($error) alert('Masukan Nilai')
    else {
      $title = '<input type="text" name="imageTitles[]" placeholder="Title" />';
      $file = '<div class="uneditable-input"><i class="icon-file fileupload-exists"></i> <span class="fileupload-preview"></span></div><span class="btn btn-file"><span class="fileupload-new">Select</span><input type="file"  accept=".jpg, .jpeg" name="images[]" onchange="change($(this))"></span>';
      $delete = '<a id="field" class="btn" onclick="deleteImage($(this))">Delete</a>';
      $('table#images tbody').append("<tr><td>"+$title+"</td><td>"+$file+"</td><td>"+$delete +"</td></tr>");
    }
  }
                                                                                                                                                                                                                                                                              
  function updateTableImage() {
    if($("table#images tbody > tr").length == 0) {
      $("table#images").hide();
    }
  }
                                                                                                                                                                                                                                                                            
  $(function(){
    updateTableImage();
  })
                                                                                                                                                                                                                                                                                                                      
  function deleteImage(obj) {
    $(obj).parent().parent().remove();
    updateTableImage();
  }
                                                                                                                                                                                                                                                                                                                      
  function deleteExistingImage(obj, id) {
    $.ajax({
      url: '<?php echo $this->rootUrl() . '/admin/ajax/deleteExistingImage' ?>',
      data: 'id=' + id,
      type: 'POST',
      success: function(response){
        $(obj).parent().parent().remove();
        updateTableImage();
      }
    });
  }
</script>

<?php echo $this->render('partial/tinyMCE.phtml'); ?>
