<tr>
  <td><input type="checkbox" name="regions[]" 
                         value="<?php echo $this->area_id; ?>"/>
  </td>    
  <td>
    <a href="<?php echo $this->rootUrl(); ?>/admin/region/edit/id/<?php echo $this->area_id; ?>/lang/1"><?php echo $this->name; ?></a>
  </td>
  <td><?php echo $this->pointY . ' , ' . $this->pointX; ?></td>

  <td>
    <a href="<?php echo $this->rootUrl(); ?>/admin/region/edit/id/<?php echo $this->area_id; ?>/lang/2">
      <?php
      if ($this->CheckRegionalIndo($this->area_id, 2)):
        ?>
        <i class="icon-edit"></i>
      <?php else: ?>
        <i class="icon-pencil"></i>
      <?php endif; ?>
    </a>
    <?php
    $indtrans = $this->CheckRegionalIndoTrans($this->area_id, 2);
    if ($indtrans == true) {
      ?>
      <a href="#" onclick="deleteArea2(<?php echo $this->area_id; ?>);"><i class="icon-trash"></i></a>
    <?php } ?>
  </td>

  <td>
    <a href="<?php echo $this->rootUrl(); ?>/admin/region/edit/id/<?php echo $this->area_id; ?>/lang/1">
      <i class="icon-edit"></i></a>
    <a onclick="deleteArea(<?php echo $this->area_id; ?>);"><i class="icon-trash"></i></a>
  </td>
</tr>