<?php echo $this->render('partials/widgets/google-search.phtml'); ?>
<?php echo $this->render('partials/widgets/top-highlight-widget.phtml'); ?>
<?php echo $this->render('partials/widgets/page-shortcut-widget.phtml'); ?>
<?php echo $this->render('partials/widgets/middle-highlight-widget.phtml'); ?>
<?php echo $this->render('partials/widgets/facebook-widget.phtml'); ?>
<?php echo $this->render('partials/widgets/twitter-widget.phtml'); ?>
<?php echo $this->categoryWidget(); ?>
<?php echo $this->cultureWidget(5, true); ?>
<?php echo $this->newsWidget(5, true); ?>
<?php echo $this->eventWidget(5, true); ?>
