<?php echo $this->render('partials/widgets/google-search.phtml'); ?>
<?php echo $this->render('partials/widgets/top-highlight-widget.phtml'); ?>
<?php echo $this->render('partials/widgets/page-shortcut-widget.phtml'); ?>
<?php echo $this->render('partials/widgets/middle-highlight-widget.phtml'); ?>
<?php echo $this->render('partials/widgets/facebook-widget.phtml'); ?>
<?php echo $this->render('partials/widgets/twitter-widget.phtml'); ?>
<?php echo $this->render('partials/widgets/social-icons-widget.phtml'); ?>
<?php //echo $this->pollingWidget(); ?>
