<!--
 * IndexPackageViewer
 *
 * Viewer untuk halaman view tour package
 *
 * Code blame to: BEM
 *

 -->
<div class="section">

    <h2 class="section-title">
        <span><?php echo $this->material['title']; ?></span>
    </h2>

    <div style="margin-left: 80px; margin-right: 50px;">
        <p style="text-align: justify;">
            <?php echo $this->htmlDecode($this->material['description']); ?>
        </p>

        <ul>
            <?php foreach ($this->materialLink as $materialLink) : ?>
                <li>
                    <a href="<?php echo $materialLink['link']; ?>">
                        <?php echo $materialLink['file']; ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
    
</div>