<!--
 * PromotionMaterialViewer
 *
 * Viewer untuk halaman index promotion materials
 *
 * Code blame to: BEM
 *
 * @copyright Copyright (c) 2010 Sangkuriang Studio
 * @author Sangkuriang Studio <www.sangkuriangstudio.com>
 -->
<div class="section">
    <h2 class="section-title">
        <!-- id_menu_material = 'Promotion Materials' -->
        <span><?php echo $this->translate('id_menu_material'); ?></span>
    </h2>

    <?php echo $this->paginationControl(
            $this->material,
            'Sliding',
            'partials/pagination.phtml',
            array('message' => $this->customName, 'upMessage' => true)); ?>

    <div style="margin-left: 80px; margin-right: 50px;">
    <?php foreach($this->material as $material) : ?>
        <div class="en-promo" style="color: white; min-height: 150px; min-width: 655px; margin-left:-80px; padding-left:20px; padding-right:20px; background: url(http://cdn.indonesia.travel/media/images/index/bg_wood.jpg) no-repeat;">

            <h3>
                <!--<a href="<?php echo $this->baseUrl(
                        '/material/detail/' . $material['material_id'] . '/'
                        . $this->makeUrlFormat($material['title'])) ?>">-->
                        <?php echo $material['title']?>
                <!--</a><-->
            </h3>

            <p style="text-align: justify">
              <img src="http://cdn.indonesia.travel/download/PromotionalMaterial/images/thumbimg.jpg" align="left">  
		<?php echo $this->truncate($this->htmlDecode($material['description']), 250) ?>
		
            </p>

            <!--<span class="read-more-lb">
                <a href="<?php echo $this->baseUrl(
                        '/material/detail/' . $material['material_id'] . '/'
                        . $this->makeUrlFormat($material['title'])) ?>">
                        <?php echo $this->translate('read_more') ?> &gt;&gt;
                </a>
            </span>-->

		<p style="text-align: right; padding-right:20px;padding-top:50px;">
                <a href="<?php echo $this->baseUrl(
                        '/material/detail/' . $material['material_id'] . '/'
                        . $this->makeUrlFormat($material['title'])) ?>">
                        <?php echo $this->translate('') ?><img src="http://cdn.indonesia.travel/media/images/index/bt_more.png" border="0" alt="More"></a>
            </p>


        </div>
    <?php endforeach; ?>
    </div>

    <?php echo $this->paginationControl(
            $this->material,
            'Sliding',
            'partials/pagination.phtml',
            array('message' => $this->customName, 'downMessage' => true)); ?>



</div>