<div id="change-password-box" class="hidden">
    <div class="error-box"></div>
    <div class="success hidden">

    </div>
    <?php $form = new Form_ChangePasswordForm; ?>
    <?php echo $form ?>
</div>

<div id="change-password-message" title="Change Password Success" class="hidden">
    <p>
        <span class="ui-icon ui-icon-circle-check icon-msg"></span>
        You have been successfully changed your password
    </p>
</div>