<!-- PAGE-TITLE begins here -->
<div class="row-fluid section-title" style="border-left-color: #ff9600;">
    <div class="pull-left">
        <h1 style="font-size: 28px;"><?php echo $this->escape($this->htmlDecode($this->news['title'])); ?></h1>
    </div>
</div>
<ul class="breadcrumb">
    <li><a href="<?php echo $this->url(array(), ($this->langId == 1) ? 'beranda' : 'home'); ?>"><?php echo ($this->langId == 1) ? "Beranda" : "Home"; ?></a></li>
    <li><a href="<?php echo $this->url(array(), ($this->langId == 1 ? 'berita' : 'news')); ?>"><?php echo ($this->langId == 1) ? "berita" : "news"; ?></a></li>
    <li class="active"><?php echo $this->escape($this->htmlDecode($this->news['title'])); ?></li>
</ul>
<div class="row-fluid" >
    <div class="span24">
        <div class="row-fluid section-content">

            <div class="cont span22">
                <p class="section-metadata">
                    <?php if (!empty($this->news->created_by)): ?>
                        <?php
                        $date = "";
                        $created = new DateTime($this->news['publish_date']);
                        if ($this->langId == 1) {
                            $month = $this->month($created->format('m'), 2);
                            $date = "Dipublish <strong>" . $month . ' ' . $created->format('j, Y') . "</strong>";
                        } else {
                            $date = "Published <strong>" . $created->format("F j, Y") . "</strong>";
                        }
                        ?>
                        <span><?php echo $this->translate('by') . ' <b>' . $this->news->created_by . '</b>' ?></span>                
                        <b> &middot; </b>
                        <span>
                            <time datetime="<?php echo $this->news['publish_date']; ?>">
                                <?php echo $date; ?>
                            </time>
                        </span>
                    <?php endif; ?>
                </p>
                <div id="news-content">
                    <?php if (file_exists(UPLOAD_FOLDER . '/news/' . $this->news['image']) && !empty($this->news['image'])) : ?>
                        <div id="news-img" class="center">
                            <img class="center" src="<?php
                                 echo $this->imageUrl(
                                         'upload/news/' . $this->news['image']);
                                 ?>"
                                 alt="<?php echo $this->news['image']; ?>" />
                        </div>
                    <?php endif; ?>
                    <?php echo $this->htmlDecode($this->news['content']); ?>
                </div>
            </div>
        </div>
    </div>
</div>