<?php echo $this->render('partial/flashMessenger.phtml'); ?>

<form action="" method="post">
    <?php echo $this->render('partial/pageFilter.phtml'); ?>
    <div class="row-fluid">
        <table class="table table-striped table-hover" id="table-admin">
            <col width="5%"/>
            <col width="15%"/>
            <col width="25%"/>
            <col width="30%"/>
            <col width="15%"/>
            <col width="10%"/>
            <thead>
                <tr>
                    <th>
                        <input type="checkbox" onclick="
                                if ($(this).attr('checked')) {
                                    $('#table-admin tbody input:checkbox').attr('checked', true);
                                } else {
                                    $('#table-admin tbody input:checkbox').removeAttr('checked');
                                }
                               ">
                    </th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Nama Lengkap</th>
                    <th>Role</th>
                    <th></th>
                </tr>
                <tr>
                    <th></th>
                    <th>
                        <?php
                        echo $this->formText('filter[username]', $this->filter['username'], array(
                            'class' => 'span12',
                            'placeholder' => 'Cari berdasarkan username...'
                        ));
                        ?>
                    </th>
                    <th>
                        <?php
                        echo $this->formText('filter[email]', $this->filter['email'], array(
                            'class' => 'span12',
                            'placeholder' => 'Cari email...'
                        ));
                        ?>
                    </th>
                    <th>
                        <?php
                        echo $this->formText('filter[name]', $this->filter['name'], array(
                            'class' => 'span12',
                            'placeholder' => 'Cari nama lengkap...'
                        ));
                        ?>
                    </th>
                    <th>
                        <?php
                        $select = array(
                            null => 'Tampilkan Semua',
                            9 => 'Administrator',
                            13 => 'Contributor',
                            12 => 'Editor');
                        echo $this->formSelect('filter[type]', $this->filter['type']
                                , array('class' => 'span12'), $select);
                        ?>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $index => $account): ?>
                    <?php
                    $delete_url = $this->url(array(
                        'action' => 'delete',
                        'id' => $account->admin_id
                    ));
                    $update_url = $this->url(array(
                        'action' => 'edit',
                        'id' => $account->admin_id
                    ));
                    ?>
                    <tr>
                        <td class="text-center">
                            <input type="checkbox" name="account[]" value="<?php echo $account->admin_id; ?>"/>
                        </td>
                        <td><?php echo $account->username; ?></td>
                        <td><?php echo $account->email; ?></td>
                        <td><?php echo $account->name; ?></td>
                        <td><?php echo $account->role_name; ?></td>
                        <td class="text-center">
                            <a href="<?php echo $update_url; ?>" title="Sunting">
                                <span class="rulycon-pencil"></span>
                            </a>
                            <a href="<?php echo $delete_url; ?>" 
                               title="Hapus" 
                               onclick="if (!confirm('Apakah anda yakin ingin menghapus akun ini?'))
                                           return false">
                                <span class="rulycon-remove-2"></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>