<!--main-->
<div id="main-destdisc">

    <!--main content-->
    <div id="wrapper-content">
        
        <!--Breadcumb-->
        <div id="breadcumb">
            <?php echo $this->breadcrumb() ?>
        </div>    
        <!--End Breadcumb-->

        <?php echo $this->render('destination/destination-title.phtml'); ?>

        <!--content tab-->
        <div id="content-tab-dest" class="destinasi">


            <div id="dest-content">
                <a name="firstsection"></a>
                <h2 class="section-title">
                    <span><?php echo $this->pageTitle ?></span>
                </h2>
                <div class="section">
                    <?php echo $this->form ?>
                </div>
            </div>
      



        </div>

    </div>


    <!--sidebar-->
    <?php
        echo $this->render('destination/sidebar-new.phtml');
    ?>                          
    <!--end sidebar -->

</div>


<?php echo $this->render('destination/destination-footer.phtml'); ?>



<?php $this->placeholder('jsInline')->captureStart(); ?> 
    <script type="text/javascript" src="<?php echo $this->scriptUrl('/javascripts/tiny_mce/tiny_mce.js') ?>"></script>
    <script type="text/javascript">
    
    tinyMCE.init({
            // General options
            mode : "textareas",
            theme : "advanced",
            plugins : "safari,pagebreak,style,layer,table,save,advhr,advimage,advlink,emotions,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,print,contextmenu,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template,wordcount",

            // Theme options
            theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull",
            theme_advanced_buttons2 : "cut,copy,paste,pastetext,pasteword,|,search,replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,image",
            theme_advanced_buttons3 : "",
            theme_advanced_toolbar_location : "top",
            theme_advanced_toolbar_align : "left",
            theme_advanced_statusbar_location : "bottom",
            theme_advanced_resizing : false,

            // Example content CSS (should be your site CSS)
            content_css : "css/content.css",

            // Drop lists for link/image/media/template dialogs
            template_external_list_url : "lists/template_list.js",
            external_link_list_url : "lists/link_list.js",
            external_image_list_url : "lists/image_list.js",
            media_external_list_url : "lists/media_list.js"

        });
    </script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>

