<?php foreach ($this->messages as $index => $message): ?>
    <div class="alert alert-success">   
        <a href="#" data-dismiss="alert" class="close">x</a> 
        <strong><?php echo $message; ?></strong> 
    </div>
<?php endforeach; ?>
<form action="" method="post">  
    <?php
    echo $this->formHidden('action', 'sort');
    echo $this->formHidden('filter[sort]', $this->filter['sort']);
    echo $this->formHidden('filter[order]', $this->filter['order']);
    ?> 
    <div class="row-fluid">    
        <h3 class="page-title">
            <span>Galeri Kebudayaan</span>
        </h3>    
        <div class="pull-left">      
            <a href="<?php echo $this->url(array('action' => 'add')); ?>" class="btn btn-red btn-with-icon"> 
                <span class="rulycon-plus"></span> Tambah Gambar      
            </a>
        </div>  
    </div>  
    <hr>  
    <div class="row-fluid">   
        <div class="row-fluid">      
            <div class="pull-left">        
                <button name="action" value="filter" style="visibility: hidden;position: absolute"></button>
                <button name="action" value="delete" class="btn btn-cyan btn-icon-only" 
                        onclick="if (!confirm('Apakah anda yakin ingin menghapus semua gambar yang dipilih?'))
                                    return false">          
                    <span class="rulycon-remove-2"></span>
                </button>
                <button class="btn btn-cyan" name="action" value="filter">Gunakan Filter</button>
                <button name="action" value="reset" class="btn btn-cyan">Atur Ulang Filter</button>
            </div>
            <div class="pull-right">      
                <?php echo $this->paginationControl($this->images, 'sliding', 'partial/pagination_control.phtml'); ?>  
            </div>
        </div>
        <div class="row-fluid">
            <table class="table table-striped table-hover" id="tabel-event">
                <colgroup>
                    <col width="1%" />
                    <col width="5%" />
                    <col width="15%" />
                    <col width="30%" />
                    <col width="30%" />
                    <col width="15%" />
                    <col width="5%" />
                </colgroup>
                <thead>
                    <tr>
                        <th>
                            <input type="checkbox" name="" id="" onclick="
                                    var checkboxes = ('#tabel-event tbody input:checkbox');
                                    if ($(this).attr('checked'))
                                        $(checkboxes).attr('checked', true);
                                    else
                                        $(checkboxes).removeAttr('checked');"/>            
                        </th>            
                        <th>Gambar</th> 
                        <th>Sumber</th>
                        <th>Keterangan</th>
                        <th>Keterangan (EN)</th>
                        <th>Dibuat</th>
                        <th></th>
                    </tr>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>   
                        <th>
                            <?php
                            echo $this->formText('filter[caption]', $this->filter['caption'], array(
                                'class' => 'span12',
                                'style' => 'margin-bottom: 5px',
                                'placeholder' => 'Ketikan keterangan gambar untuk pencarian...'));
                            ?>
                        </th>
                        <th>
                            <?php
                            echo $this->formText('filter[caption_en]', $this->filter['caption_en'], array(
                                'class' => 'span12',
                                'style' => 'margin-bottom: 5px',
                                'placeholder' => 'Ketikan translasi untuk pencarian...'));
                            ?>
                        </th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->images as $index => $image): ?>
                        <tr>
                            <td class="text-center">
                                <input type="checkbox" name="images[]" value="<?php echo $image->id; ?>"/>
                            </td>
                            <td>
                                <?php
                                $src = 'default.jpg';
                                $w = 75;
                                $h = 75;
                                $q = 100;
                                if (is_file(UPLOAD_FOLDER . 'gallery/' . $image->image)) {
                                    $src = "upload/gallery/{$image->image}";
                                }
                                $timthumb = $this->imageUrl("timthumb.php?src={$src}&w={$w}&h={$h}&q={$q}")
                                ?>
                                <a href="<?php echo $this->imageUrl("upload/gallery/{$image->image}"); ?>" rel="prettyPhoto">
                                    <img src="<?php echo $timthumb; ?>" alt="" class="thumbnail" title="<?php echo $image->caption; ?>"/>
                                </a>
                            </td>
                            <td><?php echo $image->source; ?></td>
                            <td><?php echo $image->caption; ?></td>
                            <td><i><?php echo $image->caption_en; ?></i></td>
                            <td>
                                <small>
                                    <strong>
                                        <?php echo date("F j, Y", strtotime($image->created_at)); ?>
                                        <small><?php echo date('H:i', strtotime($image->created_at)); ?></small>
                                    </strong>
                                    <div>
                                        Oleh
                                        <strong>
                                            <?php echo ucfirst(empty($image->name) ? $image->username : $image->name); ?>
                                        </strong>
                                    </div>
                                </small>
                            </td>
                            <td class="text-center">
                                <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $image->id)); ?>"
                                   title="Sunting">
                                    <span class="rulycon-pencil"></span>     
                                </a>                                                 
                                <a onclick="
                                            if (!confirm('Apakah anda yakin ingin ' + 'menghapus gambar ini?'))
                                                return false" 
                                   href="<?php echo $this->url(array('action' => 'delete', 'id' => $image->id)); ?>" 
                                   title="Hapus">     
                                    <span class="rulycon-remove-2"></span>     
                                </a>             
                            </td>       
                        </tr>         
                    <?php endforeach; ?>    
                </tbody>    
            </table>   
        </div>  
    </div>
</form>

<?php $this->placeholder('jsInline')->captureStart(); ?>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $("a[rel^='prettyPhoto']").prettyPhoto({social_tools: false});
    });
</script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>