<div class="one-column">
    <div class="space">
    <h2 class="section-title"><span><?php echo $this->translate('Culture Chart') ?></span></h2>    
    <p>
        <?php echo $this->translate('Category'); ?>         
        <select name="category" id="main-category">
            <option value="all"><?php echo $this->translate("All Main Categories") ?></option>
            <?php foreach($this->categories as $category): ?>
                <option value="<?php echo $category['category_id'] ?>"><?php echo $category['name'] ?></option>
            <?php endforeach; ?>
        </select>
    </p>
    <p>
        <button id="filter-chart" class="button button-grey"><?php echo $this->translate('Filter') ?></button>
        <span id="filter-loading" class="hide"><img src="<?php echo $this->imageUrl('indicator.gif') ?>" /></span>
    </p>    
    </div>
    <div id="category-chart"></div>    
</div><!-- end div section -->

<?php $this->placeholder('jsInline')->captureStart(); ?>
    <script type="text/javascript" src="<?php echo $this->scriptUrl('javascripts/frontend/lib/highcharts/js/highcharts.js') ?>"></script>    
    
    <?php 
        if(APPLICATION_ENV == "production" || APPLICATION_ENV == "testing") {
            $chartJs = 'javascripts/frontend/chart.min.js';
        } else {
            $chartJs = 'javascripts/frontend/chart.js';
        }
    ?>
        
    <script type="text/javascript" src="<?php echo $this->scriptUrl($chartJs) ?>"></script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>
