<div class="filter-panel">
<h4 style="margin-right: 5px; margin-top: 10px;">Filter:</h4>
<form action="<?php echo $this->currentUrl(); ?>" method="post">
    <select class="filter-box" name="filterPage" id="filterPage"
                onchange="filterSwitch(this.value);">
            <option value="0">Show All</option>
            <option value="1">Name</option>
    </select>
    <input type="text" class="name-box mediumele hidden" name="filterName"/>
    
    <input type="submit" value="Go" class="btn radius" />
    <span class="ajax-loader"></span>
</form>
</div>