<?php $this->placeholder('styles')->captureStart(); ?>
<link href="<?php echo $this->scriptUrl('/styles/table-css.php'); ?>" rel="stylesheet" type="text/css" />
<?php $this->placeholder('styles')->captureEnd(); ?>
<!-- print out any message from create/saved page proccess-->
<?php
    if (!empty($this->message)) {
        foreach ($this->message as $warn) echo $this->flashMessage($warn);
    }
?>
<h2>Airlines Menu</h2>
<h3  class="wide">Create, Update, or Delete from the list</h3>
<div class="table-container">
    <input type="button" class="btn radius" style="margin-bottom:10px;"
           value="+ Add New Airline"
           onclick="window.location='<?php echo $this->rootUrl('admin/airlines/create'); ?>'"/>
    <br class="clearfloat" />
    <?php echo $this->partial('airlines/filter-panel.phtml')."\n"; ?>
    <?php echo $this->render('partial/page-filter.phtml'); ?>

    <!-- generating alert on filter selected -->
    <br class="clearfloat" />
    <?php if (!empty($this->alert)) : ?>
        <div class="tip"> Current filter selected: <?php echo $this->alert; ?>
        </div>
    <?php endif; ?> 

    <?php if(count($this->paginator)>0) :?>
        <?php echo $this->paginationControl($this->paginator,'Sliding','partial/pagination-control.phtml'); ?>
    <br class="clearfloat"  />
        <br class="clearfloat"  />
        <table style="width:100%;" cellspacing="0">
                <?php echo $this->partial('airlines/table-header.phtml')."\n"; ?>
            <tbody>

                    <?php $row_index = 0; ?>
                    <?php echo $this->partialLoop('airlines/table-row.phtml',$this->paginator)."\n"; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginator,'Sliding','partial/pagination-control.phtml'); ?>
    <br class="clearfloat"  />
    <?php endif; ?>
    <br class="clearfloat"  />
</div>

<div id="processLoader" class="hidden">
    <img src='<?php echo $this->imageUrl('ajax-loader-big.gif'); ?>'/>
</div>

<?php 
$this->placeholder('jsInline')->captureStart();
?>
<script type="text/javascript">
    function deleteAirlines(airline_id)
    {
        if(confirm('Are you sure you want to delete this airline?'))
        {
            tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
            $.ajax({
                type: "POST",
                url: "<?php echo $this->rootUrl().'/admin/ajax/deleteairline'; ?>",
                data: {airline_id:airline_id},
                success: function(data){
                    window.location.reload(true);
                },
                error: function(){alert('Error Occured, please report this to the developer');}
            });        
        }
    }

    function filterSwitch(value)
    {

        switch(value)
        {
            case "0": hideAllFilter();
                break;
            case "1": hideAllFilter();
                $('.name-box').fadeIn('slow');
                $('.filter-btn').fadeIn('slow');
                break;
        }
    }

    function hideAllFilter()
    {
        $('.name-box').hide();
    }

    function getAllCheckBoxes(elform, elname) {
        var hasil = Array();
        var n = 0;
        for (var i=0; i<elform.elements.length; i++) {
            if (elform.elements[i].type == 'checkbox' && elform.elements[i].name == elname) {
                hasil[n++] = elform.elements[i];
            }
        }
        return hasil;
    }

    var checkedAll = false;
    var chk = getAllCheckBoxes(document.contact, 'contact_item[]');

    function checkBoxAll(){
        if (!checkedAll) {
            checkedAll = true;
            for (i = 0; i < chk.length; i++)
                chk[i].checked = true;
        } else {
            checkedAll = false;
            for (i = 0; i < chk.length; i++)
                chk[i].checked = false;
        }
    }

</script>
<script type="text/javascript">
    <!--

    function doSubmit(action) {
        var eform = document.contact;
        for (i = 0; i < eform.elements.length; i++){
            if (eform.elements[i].type == 'checkbox')
                if(eform.elements[i].checked){
                    switch (action) {
                        case 'delete_selected':
                            if (confirm("This will delete multiple email. Proceed? ")) {
                                eform.actionnya.value = 'delete_selected';
                                eform.submit();
                            }
                            break;
                        case 'toggle_flag_selected':
                            eform.actionnya.value = 'toggle_flag_selected';
                            eform.submit();
                            break;
                        case 'flag_selected':
                            eform.actionnya.value = 'flag_selected';
                            eform.submit();
                            break;
                        case 'unflag_selected':
                            eform.actionnya.value = 'unflag_selected';
                            eform.submit();
                            break;
                        default:
                        //do nothing
                }
        }
    }

}

//-->
</script>

<?php $this->placeholder('jsInline')->captureEnd(); ?>