<!--

 * NewsViewer

 *

 * Viewer untuk halaman index news

 *

 * @copyright Copyright (c) 2010 Sangkuriang Studio

 * @author Sangkuriang Studio <www.sangkuriangstudio.com>

 -->

 <style type="text/css">
    .selection {
        display: none;
    }
</style>

<div class="row-fluid">
    <div class="span24">
        <h1 id="page-title" class="text-center"><span>Kebudayaan Indonesia</span></h1>
    </div>
</div>


    <a name="firstsection"></a>

    <?php $trw = 1; ?>

<!-- view for pagination-->
    <div class="paginate" style="margin-bottom:20px !important">
    </div>
<!-- -->

<div class="row-fluid span24" id="news-section">
        
        <!-- id_menu_news = News -->
        <h2 class="news-section-title <?php echo $this->colorClass ?> span3">

            <span><?php echo $this->menuTitle; ?></span>

        </h2>
</div>

<div class="selection" id="page-<?php echo $trw; ?>" style="margin-top: 0px !important;">
   <?php $tr = 1;
   foreach($this->news as $key => $news) : ?>

    <div class="row-fluid" id="spacing">

            <div class ="images span6" >

                <a class="zoom" title="<?php echo $news['title']; ?>" 

                   href="<?php echo $this->imageUrl('/upload/news/' . $news['image']); ?>">

                    <?php if ((file_exists(UPLOAD_FOLDER . 'news/' . $news['image'])) && !empty($news['image'])) : ?>

                        <img src="<?php echo $this->imageUrl('/upload/news/' . $news['image']); ?>"

                             alt="<?php echo $news['title']; ?>" style="max-width: 150px; max-height: 130px;"/>

                    <?php else : ?>

                        <img src="<?php echo $this->imageUrl('default.jpg'); ?>"

                             alt="<?php echo $news['title']; ?>" />

                    <?php endif; ?>

                </a>
            </div>

            <div class="keterangan span18">
                <h3>

                    <a href="<?php echo $this->baseUrl(

                            '/news/detail/' . $news['news_id'] . '/'

                            . $this->makeUrlFormat($news['title'])); ?>" class="judul">

                        <?php echo $this->escape($news['title']); ?>

                    </a>

                </h3>



                <p class="section-metadata">

                    <span class="date"><?php echo $this->newsMeta($news['publish_date']); ?></span>

                </p>



                <p>

                    <?php echo $this->truncate($news['content'], 250); ?>

                </p>



                <span class="read-more-lb">

                    <a class="s-btn s-btn-orange" href="<?php echo $this->baseUrl(

                            '/news/detail/' . $news['news_id'] . '/'

                            . $this->makeUrlFormat($news['title'])); ?>">

                            <?php echo $this->translate('id_read_more_new'); ?>

                    </a>

                </span>
            </div>
        <div>
    </div>
</div>

    <!-- Paging Logic -->
    <?php if($key + 1 == $this->count): ?>
        </div>
    <?php elseif($key > 0 && $tr % 5 == 0): ?>
            <?php $trw++; ?>
            </div>
            <div class="selection" id="page-<?php echo $trw; ?>">
    <?php endif; ?>
    <?php $tr++; ?>
    <?php endforeach; ?>
    <!-- -->

<!-- view for pagination -->
<div class="paginate">
</div>
<!-- -->

<?php $this->placeholder('jsInline')->captureStart(); ?>
<script type="text/javascript">

    $(document).ready(function(){
        test(0);
    });

    function test(pageNumber)
    {
        if(pageNumber == '' || pageNumber ==  null || pageNumber == 0)
        {
            pageNumber = 1;
        }
      var page="#page-"+pageNumber;
      $('.selection').hide()
      $(page).show()

    }

    $(function() {
    $(".paginate").pagination({
        items: '<?php echo $this->count; ?>',
        itemsOnPage: 5,
        cssStyle: 'light-theme',
        onPageClick: function(pageNumber){test(pageNumber)}
    });
});
</script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>