<!--<ul class="socialicons color">
                <li><a href="<?php echo $this->baseUrl('/news/rss'); ?>" class="rss" target="_blank">rss</a></li>
                <li><a href="http://facebook.com/pages/Indonesia-Berbudaya/127999584019830" class="facebook" target="_blank">facebook</a></li>
                <li><a href="http://twitter.com/budayasaya" class="twitter" target="_blank">twitterbird</a></li>
                <li><a href="https://plus.google.com/u/0/105485413132575433204" class="gpluslight" target="_blank">gpluslight</a></li>
                <li><a href="http://pinterest.com/lamanbudaya" class="pinterest" target="_blank">pinterest</a></li>
              </ul>
<div class="clear"></div>-->
<h2 class="widget-title black">
    IKUTI KAMI
</h2>
<ul class="socialmedia">
    <li><a href="http://pinterest.com/lamanbudaya" target="_blank" class="pinterest"></a></li>
    <li><a href="http://facebook.com/pages/Indonesia-Berbudaya/127999584019830" target="_blank" class="facebook"></a></li>
    <li><a href="http://twitter.com/budayasaya" target="_blank" class="twitter"></a></li>
    <li><a href="https://plus.google.com/u/0/105485413132575433204" target="_blank" class="gplus"></a></li>
    <li><a href="<?php echo $this->baseUrl('/news/rss'); ?>" target="_blank" class="rss"></a></li>
</ul>