<div class="filter-panel filter-hidden">
    
    <h4 style="margin-top: 10px;"><label for="filterPage">Filter:</label></h4>
    
    <form action="<?php echo $this->currentUrl(); ?>" method="post">
        <select class="filter-box" name="filterType" id="filterPage">
            <?php foreach ($this->type as $key => $value) : ?>
                <option value="<?php echo $key; ?>">
                    <?php echo $value; ?>
                </option>
            <?php endforeach; ?>
        </select>
        
        <input type="submit" value="Go" class="btn radius"/>
    </form>
</div>