<?php $this->placeholder('styles')->captureStart(); ?>
<link href="<?php echo $this->scriptUrl('/styles/table-css.php'); ?>" rel="stylesheet" type="text/css" />
<?php $this->placeholder('styles')->captureEnd(); ?>

<!-- print out any message from create/saved page proccess-->
<?php
if (!empty($this->message)) {
  foreach ($this->message as $warn)
    echo $this->flashMessage($warn);
}
?>

<h2>Related Links Menu</h2>
<h3 class="wide">Create, Update, or Delete from the list</h3>
<div class="table-container">
  <input type="button" style="margin-bottom:10px;" class="btn radius" value="+ Add Related Links" onclick="window.location='<?php echo $this->rootUrl('admin/relatedlinks/create'); ?>'"/>
  <br class="clearfloat"  />
  <?php $panel_data = array('type' => $this->related_type); ?>
  <?php echo $this->render('partial/page-filter.phtml'); ?>


  <!--Filter panel-->
  <div class="filter-panel filter-hidden">

    <form action="<?php echo $this->currentUrl(); ?>" method="post" class="form-inline well">
      <label for="filterPage" class="control-label">Filter:</label>
      <select class="filter-box" name="filterType" id="filterPage">
        <?php foreach ($this->related_type as $key => $value) : ?>
          <option value="<?php echo $key; ?>">
            <?php echo $value; ?>
          </option>
        <?php endforeach; ?>
      </select>
      <input type="submit" value="Go" class="btn radius"/>

      <hr />
      <?php if (!empty($this->alert)) : ?>
        <div class="tip"> Current filter selected: <?php echo $this->alert; ?>
        </div>
      <?php endif; ?> 
    </form>
  </div>
  <!--/filter panel-->

  <!-- generating alert on filter selected -->

  <br class="clearfloat"  />
  <?php if (count($this->paginator) > 0) : ?>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination-control.phtml'); ?>
    <br class="clearfloat"  />

    <table style="width:100%;" cellspacing="0" class="table table-bordered table-striped">
      <?php echo $this->partial('relatedlinks/table-header.phtml') . "\n"; ?>
      <tbody>
        <?php $row_index = 0; ?>                        
        <?php echo $this->partialLoop('relatedlinks/table-row.phtml', $this->paginator) . "\n"; ?>
      </tbody>
    </table>

    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination-control.phtml'); ?>
    <br class="clearfloat"  />
  <?php endif; ?>
  <br class="clearfloat"  />
</div>

<div id="processLoader" class="hidden">
  <img src='<?php echo $this->imageUrl('ajax-loader-big.gif'); ?>'/>
</div>

<?php
$this->placeholder('jsInline')->captureStart();
?>
<script type="text/javascript">
  function deleteRelated(related_id)
  {
    if(confirm('Are you sure you want to delete this related link?'))
    {
      tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
      $.ajax({
        type: "POST",
        url: "<?php echo $this->rootUrl() . '/admin/ajax/deleterelated'; ?>",
        data: {relatedid:related_id},
        success: function(data){
          window.location.reload(true);
        },
        error: function(){alert('Error Occured, please report this to the developer');}
      });        
    }
  }
  function deleteRelatedIndo(related_id,lang_id)
  {  
    if(confirm('Are you sure you want to delete this related link?'))
    {
      tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
      $.ajax({
        type: "POST",
        url: "<?php echo $this->rootUrl() . '/admin/ajax/deleterelatedindo'; ?>",
        data: {relatedid:related_id,langid:lang_id},
        success: function(data){
          window.location.reload(true);
        },
        error: function(){alert('Error Occured, please report this to the developer');}
      });        
    }
  }
    
  $(function(){
    $('.filter-panel').show();
  });
</script> 
<?php $this->placeholder('jsInline')->captureEnd(); ?>