<!--<div class="row-fluid">
  <h3 class="pull-left">Cultures</h3>
  <div class="pull-right">
    <form class="form-search">
      <div class="input-append">
        <input type="text" class="search-query" placeholder="Type culture name here..">
        <button type="submit" class="btn">Search</button>
      </div>
    </form>
  </div>
</div>

<div class="row-fluid">
  <form action="">
    <div class="row-fluid">
      <div class="span3">
        <button class="btn btn-mini" type="submit" name="delete" 
                onclick="if(!confirm('Are you sure want to delete these item ?')) return false;">
          <i class="icon-trash"></i>
        </button>
        <button class="btn btn-small">Apply Filter</button>
        <a class="btn btn-primary btn-small" title="Add culture">
          Create
        </a>
      </div>
      <div class="span5 offset4">
        <div class="pull-right">
          <div class="pagination" style="margin: 0">
            <ul>
              <li><a class="disabled" href="#">Prev</a></li>
              <li><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a class="active" href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#">Next</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span12">
        <table class="table table-striped table-condensed" id="tb-culture">
          <col width="1%" />
          <col width="20%" />
          <col width="" />
          <col width="" />
          <col width="" />
          <col width="" />
          <col width="" />
          <col width="" />
          <col width="" />
          <thead>
            <tr>
              <th>
                <input type="checkbox" onchange="
                  if($(this).attr('checked'))
                    $('#tb-culture input[type=checkbox]')
                  .attr('checked', true);
                  else 
                    $('#tb-culture input[type=checkbox]')
                  .removeAttr('checked');
                       ">
              </th>
              <th>Name</th>
              <th>Area</th>
              <th>Category</th>
              <th>Author</th>
              <th><i class="icon-eye-open"></i></th>
              <th>EN</th>
              <th class="hidden-phone hidden-tablet">Date</th>
              <th></th>
            </tr>
            <tr>
              <th></th>
              <th>
                <select name="" class="span12" id="">
                  <option value="">View All Status</option>
                  <option value="">Draft</option>
                  <option value="">Pending</option>
                  <option value="">Publish</option>
                </select>
              </th>
              <th>
                <select name="" class="span12" id="">
                  <option value="">View All Area</option>
                  <option value=""></option>
                  <option value=""></option>
                </select>
              </th>
              <th>
                <select name=""class="span12" id="">
                  <option value="">View All Categories</option>
                  <option value=""></option>
                  <option value=""></option>
                </select>
              </th>
              <th></th>
              <th></th>
              <th class="hidden-phone hidden-tablet"></th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($this->paginator as $culture): ?>
              <tr>
                <td><input type="checkbox" name="" id="" /></td>
                <td>
                  <a href=""><strong><?php echo $culture->name; ?></strong></a>
                  <br />
                  <?php if ($culture->status == "PUBLISH"): ?>
                    <small class="text text-success">Publish</small>
                  <?php endif; ?>
                  <?php if ($culture->status == "PENDING"): ?>
                    <small class="text text-warning">Need approval</small>
                  <?php endif; ?>
                  <?php if ($culture->status == "DRAFT"): ?>
                    <small class="text muted">Draft</small>
                  <?php endif; ?>
                  <?php if ($culture->featured): ?>
                    <small class="text-info">Featured</small>
                  <?php endif; ?>
                </td>
                <td><?php echo $culture->area; ?></td>
                <td><?php echo $culture->category; ?></td>
                <td><?php echo $culture->created_by; ?></td>
                <td>
                  <span title="Viewer" class="badge badge-info">
                    <?php echo $culture->viewer; ?>
                  </span>
                </td>
                <td><a href="#"><i class="icon-pencil"></i></a></td>
                <td class="hidden-phone hidden-tablet">
                  <?php if (null != $culture->updated_by): ?>
                    <small>
                      Last updated on
                      <?php echo $culture->updated_at ?> <br />
                      by
                      <?php echo ucfirst($culture->updated_by); ?></small>
                  <?php elseif (null != $culture->approved_by): ?>
                    <small>Approved By
                      <?php echo ucfirst($culture->approved_by); ?></small>
                  <?php endif; ?>
                </td>
                <td>
                  <a href="" title="Edit"><i class="icon-edit"></i></a>
                  <a href="" title="Delete"><i class="icon-trash"></i></a>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      </div>
    </div>
  </form>
</div>-->
