<div id="wrapper-content">
  <h1>An error occurred please report to the Developer</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if ('development' == APPLICATION_ENV || DISPLAY_ERROR == true): ?>
      <h3>Exception information:</h3>
      <p>
          <b>Message:</b> <?php echo $this->exception->getMessage() ?>
      </p>

      <h3>Stack trace:</h3>
      <pre><?php echo $this->exception->getTraceAsString() ?>
      </pre>

      <h3>Request Parameters:</h3>
      <pre><?php echo var_export($this->request->getParams(), true) ?>
      </pre>
  <?php endif ?>
</div>