<div class="section">
    <h2 id="international-title"><span><?php echo $this->controller ?></span></h2>

    <?php echo $this->paginationControl($this->international, 'Sliding',
                    'partials/pagination.phtml',
                    array('message' => $this->controller, 'upMessage' => true)); ?>
        
    <?php foreach($this->international as $international) : ?>
        <div class="en-list">
                <h3>
                    <a href="<?php echo $this->baseUrl('/international/view/id/' .
                                            $international['international_id'] . '/' .
                                            $this->makeUrlFormat($international['title'])) ?>">
                        <?php echo $international['title']?>
                    </a>
                </h3>
                <p>
                    <?php echo $this->truncate($international['description'], 250) ?>
                </p>
                <?php echo $this->partial('partials/read-more.phtml',
                                array(
                                      'controller' => $this->controller,
                                      'id' => $international['international_id'],
                                      'title' => $international['title'],
                                      'readMore' => 'Read More'
                                )); ?>
        </div>
    <?php endforeach; ?>

    <?php echo $this->paginationControl($this->international, 'Sliding',
                    'partials/pagination.phtml',
                    array('message' => $this->controller, 'downMessage' => true)); ?>

</div>