<div id="sidebar-highlight"><img src="<?php echo $this->mediaUrl('highlight/'.$this->highlight_image[0]['image']) ?>" alt="e<?php echo $this->highlight_image[0]['image']; ?>"/></div>
<div id="sidebar-mapOfIndonesia"></div>
<div class="sidebar-shortCut"><a href="#">Plan your Trip in Indonesia</a></div>
<div class="sidebar-shortCut"><a href="#">Travel Packages</a></div>
<div class="sidebar-shortCut"><a href="#">Overseas Representatives</a></div>
<div class="sidebar-shortCut"><a href="#">Promotional Materials</a></div>
<div class="sidebar-findDirectory"></div>
<div class="sidebar-eventImage">
    <img src="<?php echo $this->mediaUrl('index/event highlight.png') ?>" />
</div>

<div class="sidebar-socialBox">
    <div class="sidebar-socialImage sidebar-facebook"><span  style="display: none;">facebook</span></div>
    <div class="sidebar-socialText"><a href="#">Became Our Fans in Facebooks</a></div>
</div>

<div class="sidebar-socialBox">
    <div class="sidebar-socialImage sidebar-twitter"><span  style="display: none;">twiter</span></div>
    <div class="sidebar-socialText" style="padding-top: 5px;"><a href="#">Follow Us On Twiter</a></div>
</div>

<div id="sidebar-linkContainer">
    <div class="sidebar-link sidebarGaruda"></div>
    <div class="sidebar-link sidebarBudpar"></div>
</div>
