<?php
$control    = $this->paginationControl($this->paginator, 'sliding',
        'partial/pagination_control.phtml');
$create_url = $this->url(array('action' => 'create'));
?>

<?php foreach ($this->messages as $key => $message): ?>
  <div class="alert alert-success">
    <a href=""
       data-dismiss="alert"
       class="close">x</a>
    <strong><?php echo $message; ?></strong>
  </div>
<?php endforeach; ?>

<div class="row-fluid">
  <h3>Articles</h3>
</div>

<div class="row-fluid">
  <form action="" method="post">
    <div class="row-fluid">
      <div class="span4">
        <button type="submit"
                name="action"
                style="
                visibility: hidden;
                position: absolute"
                value="filter">
        </button>
        <button type="submit"
                class="btn btn-mini"
                name="action"
                value="delete"
                onclick="if(!confirm('Apakah anda yakin ingin'+
                    ' Menghapus artikel ini?')) return false">
          <i class="icon-trash"></i>
        </button>
        <button type="submit"
                class="btn btn-mini"
                name="action"
                value="filter">
          <i class="icon-filter"></i>
          Apply Filter
        </button>
        <button type="submit"
                class="btn btn-mini"
                name="action"
                value="reset"
                tabindex="1">
          <i class="icon-refresh"></i>
          Reset Filter
        </button>
        <a href="<?php echo $create_url; ?>" 
           class="btn btn-mini btn-primary">
          <i class="icon-plus-sign"></i>
          Add Article
        </a>
      </div>
      <div class="span5 offset3">
        <?php echo $control; ?>
      </div>
    </div>
    <div class="row-fluid">
      <table class="table table-striped table-condensed"
             id="table-article"
             style="margin-bottom: 0">
        <col width="1%" />
        <col width="6%" />
        <col width="18%" />
        <col width="12%" />
        <col width="20%" />
        <col width="20%" />
        <col width="3%" />
        <col width="3%" />
        <thead>
          <tr>
            <th><input type="checkbox"
                       onclick="
                         if($(this).attr('checked') == true){
                           $('#table-article tbody input:checkbox')
                           .attr('checked', true);
                         }
                     else {
                       $('#table-article tbody input:checkbox')
                       .removeAttr('checked');
                     }
                       ">
            </th>
            <th>Nama</th>
            <th></th>
            <th>Status</th>
            <th>Penulis</th>
            <th>Tanggal</th>
            <th>Translasi</th>
            <th></th>
          </tr>
          <tr>
            <th></th>
            <th colspan="2">
              <input type="text" 
                     name="filter[name]" 
                     class="span12"
                     style="margin-bottom: 5px"
                     value="<?php echo $this->filter['name']; ?>"
                     placeholder="Cari judul artikel...."/>
            </th>
            <th>
              <?php
              echo $this->formSelect('filter[status]',
                      $this->filter['status'],
                      array('class' => 'span12'),
                      array(
                  null => 'Tampilkan Semua Status',
                  0    => 'Diarsipkan',
                  1    => 'Draft',
                  2    => 'Butuh Persetujuan',
                  3    => 'Diterbitkan'));
              ?>
            </th>
            <th>
              <input type="text"
                     name="filter[author]"
                     value="<?php echo $this->filter['author']; ?>"
                     class="span12" 
                     placeholder="Tampilkan semua penulis"
                     style="margin-bottom: 5px"/>
            </th>
            <th></th>
            <th></th>
            <th>
            </th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->paginator as $index => $article): ?>
            <?php
            $src = 'default.jpg';
            $w   = 50;
            $h   = 50;
            $q   = 100;

            switch ($article->status) {
              case Admin_ArticleController::STATUS_ARCHIVED:
                $status = "<small class='text muted'>Diarsipkan
                  </small>";
                break;
              case Admin_ArticleController::STATUS_DRAFT:
                $status = "<small class='text muted'>Draft
                  </small>";
                break;
              case Admin_ArticleController::STATUS_PENDING:
                $status =
                        "<small class='text text-warning'>
                          Butuh Persetujuan
                         </small>";
                if ($this->userCanApprove) {
                  $approve_url = $this->url(array(
                      'action' => 'approve',
                      'id'     => $article->id));
                  $status .=
                          "<br />
                          <a href='{$approve_url}'
                             class='btn btn-mini'>
                          Setujui</a>";
                }
                break;
              case Admin_ArticleController::STATUS_PUBLISHED:
                $status  = "<small class='text text-success'>
                  Diterbitkan</small>";
                break;
            }

            if (file_exists(UPLOAD_FOLDER . 'article/'
                            . $article->image)) {
              $src = "upload/article/{$article->image}";
            }

            $timthumb = $this->imageUrl("timthumb.php?src={$src}
              &w={$w}&h={$h}&q={$q}");

            $delete_url = $this->url(array(
                'action' => 'delete',
                'id'     => $article->id));

            $update_url = $this->url(array(
                'action' => 'update',
                'id'     => $article->id));

            $translate_url = $this->url(array(
                'action' => 'translate',
                'id'     => $article->id));

            $delete_translation_url = $this->url(array(
                'action' => 'deletetranslation',
                'id'     => $article->id));

            $edit_translation_url = $this->url(array(
                'action' => 'edittranslation',
                'id'     => $article->id));
            ?>
            <tr>
              <td>
                <input type="checkbox"
                       name="deletes[]"
                       value="<?php echo $article->id; ?>"/>
              </td>
              <td>
                <img src="<?php echo $timthumb; ?>"
                     alt=""
                     class="thumbnail"/>
              </td>
              <td>
                <strong><?php echo $article->name; ?></strong>
              </td>
              <td><?php echo $status; ?></td>
              <td><?php echo ucfirst($article->created_by); ?></td>
              <td>
                <?php if ($article->updated_by != null): ?>
                  Disunting oleh 
                  <?php echo ucfirst($article->updated_by) ?>
                  <br /> Pada 
                  <?php echo ucfirst($article->updated_at) ?>
                <?php elseif ($article->approved_by != null): ?>
                  Disetujui oleh 
                  <?php echo $article->approved_by; ?>
                  <br /> Pada   <?php echo $article->approved_at; ?>
                <?php else: ?>
                  Dibuat pada <?php echo $article->created_at ?>
                <?php endif; ?>
              </td>
              <td>
                <?php if ($article->isTranslated): ?>
                  <a href="<?php echo $edit_translation_url; ?>"
                     title="Edit translation">
                    <img src="<?php echo $this->imageUrl('icons/gCons/edit.png'); ?>" alt="" />
                  </a>
                  <a href="<?php echo $delete_translation_url; ?>"
                     title="Delete translation"
                     onclick="
                   if(!confirm(
                   'Are you sure want to delete'+
                     ' this english translation ?')) 
                     return false">
                    <img src="<?php echo $this->imageUrl('icons/gCons/delete-item.png'); ?>" 
                         alt="" />
                  </a>
                <?php else: ?>
                  <a href="<?php echo $translate_url; ?>"
                     title="Create translation">
                    <img src="<?php echo $this->imageUrl('icons/gCons/add-item.png'); ?>" alt="" />
                  </a>
                <?php endif; ?>

              </td>
              <td align="right">
                <a href="<?php echo $update_url; ?>"
                   title="Edit article">
                  <img src="<?php echo $this->imageUrl('icons/gCons/edit.png'); ?>" alt="" />
                </a>
                <a href="<?php echo $delete_url; ?>"
                   title="Delete article"
                   onclick="
                   if(!confirm('Are you sure?'))
                     return false">
                  <img src="<?php echo $this->imageUrl('icons/gCons/delete-item.png'); ?>" alt="" />
                </a>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
    <div class="row-fluid">

    </div>
  </form>
</div>
