<!--
 * ViewPackageViewer
 *
 * Viewer untuk halaman view detail tour package
 *
 * Code blame to: BEM
 *
 * @copyright Copyright (c) 2010 Sangkuriang Studio
 * @author Sangkuriang Studio <www.sangkuriangstudio.com>
 -->
<div class="section">
    <h2 class="section-title">
        <span><?php echo $this->package['title']; ?></span>
    </h2>

    <div style="margin-left: 80px;">
        <div class="" >

            <div style="float: left; width: 80px; font-weight: bold;">
                <!-- id_poi_description = 'Description' -->
                <?php echo $this->translate('id_poi_description'); ?>
            </div>

            <div class="double-dot" style="float: left; width: 10px;">:</div>

            <div style="float: left; width: 500px; text-align: justify;">
                <?php echo $this->HtmlDecode($this->package['description']); ?>
            </div>

        </div>

        <?php if (!empty ($this->package['contact'])) : ?>
            <br style="clear: both;" />

            <div class="" style="margin-top: 20px;">

                <div style="float: left; width: 80px; font-weight: bold;">
                    <!-- id_list_contact = 'Contact' -->
                    <?php echo $this->translate('id_list_contact'); ?>
                </div>

                <div class="double-dot" style="float: left; width: 10px;">:</div>

                <div style="float: left; width: 500px;">
                    <?php echo $this->package['contact']; ?>
                </div>

            </div>
        <?php endif; ?>

        <?php if (!empty ($this->package['website'])) : ?>
            <br style="clear: both;" />

            <div class="" style="margin-top: 20px;">

                <div style="float: left; width: 80px; font-weight: bold;">
                    <!-- id_list_website = 'Website' -->
                    <?php echo $this->translate('id_list_website'); ?>
                </div>

                <div class="double-dot" style="float: left; width: 10px;">:</div>

                <div style="float: left; width: 500px;">
                    <a href="<?php echo $this->package['website'] ?>">
                        <?php echo $this->package['website']; ?>
                    </a>
                </div>

            </div>
        <?php endif; ?>
    </div>
</div>