<style type="text/css">
    .selection {
        display: none;
    }
</style>

<div class="row-fluid">
    <div class="span24">
        <h1 id="page-title" class="text-center"><span>Kebudayaan Indonesia</span></h1>
    </div>
</div>

<a name="firstsection"></a>
<?php $trw = 1; ?>

<!-- view for pagination-->
<div class="paginate" style="margin-bottom:20px !important">
</div>

<div class="row-fluid span24" id="news-section">
    <!-- id_menu_news = News -->
    <h2 class="news-section-title <?php echo $this->colorClass ?> span6">
        <span><?php echo $this->pageTitle; ?></span>
    </h2>
</div>
<div class="selection" id="page-<?php echo $trw; ?>" style="margin-top: 0px !important;">
    <?php
    $tr = 1;
    foreach ($this->culture as $key => $culture):

        ?>
        <div class="row-fluid" id="spacing">
            <div class="images span6">
                <?php if ($culture['image'] != '') { ?>
                    <a href="<?php echo $this->imageUrl('/upload/culture/' . basename($culture['image'])) ?>" class="zoom">
                        <img src="<?php echo $this->imageUrl('timthumb.php?src=upload/culture/' . basename($culture['image']) . '&w=150&h=150&p=100') ?>"
                             alt="<?php echo $culture['name'] ?>" title="<?php echo $culture['name'] ?>" />
                         <?php } else { ?>
                        <img src="<?php echo $this->imageUrl('/default.jpg'); ?>"
                             alt="<?php echo $culture['name'] ?>" title="no image for this destination" />
                         <?php } ?>
                </a> 
            </div>
            <div class="keterangan span18">
                <h3>
                    <a href="<?php
                    echo $this->baseUrl('/culture/' . $culture['poi_id']
                            . '/' . $this->makeUrlFormat($culture['name']))

                    ?>">
                           <?php echo $culture['name'] ?>
                    </a>
                </h3>
                <p>
                    <?php echo $this->truncate($culture['description'], 250) ?>
                </p>

                <?php
                echo $this->partial('partials/read-more.phtml', array(
                    'controller' => $this->controller,
                    'id' => $culture['poi_id'],
                    'title' => $culture['name'],
                    'readMore' => 'Read More'
                ));

                ?>

            </div>
        </div>

        <!-- Paging Logic -->
        <?php if ($key + 1 == $this->count): ?>
        </div>
    <?php elseif ($key > 0 && $tr % 5 == 0): ?>
        <?php $trw++; ?>
        </div>
        <div class="selection" id="page-<?php echo $trw; ?>">
        <?php endif; ?>
        <?php $tr++; ?>
    <?php endforeach; ?>

    <div class="paginate"></div>

    <?php $this->placeholder('jsInline')->captureStart(); ?>
    <script type="text/javascript">

        $(document).ready(function() {
            test(0);
        });

        function test(pageNumber)
        {
            if (pageNumber == '' || pageNumber == null || pageNumber == 0)
            {
                pageNumber = 1;
            }
            var page = "#page-" + pageNumber;
            $('.selection').hide()
            $(page).show()

        }

        $(function() {
            $(".paginate").pagination({
                items: '<?php echo $this->count; ?>',
                itemsOnPage: 5,
                cssStyle: 'light-theme',
                onPageClick: function(pageNumber) {
                    test(pageNumber)
                }
            });
        });
    </script>
    <?php $this->placeholder('jsInline')->captureEnd(); ?>

