<?php

if ($this->langIId == 1) {

  $msgpagin = 'culture(s)';

} else {

  $msgpagin = 'budaya';

}

?>

<?php $trw = 1; ?>

<!-- view for pagination-->
    <!-- <div class="paginate">
    </div> -->
<!-- -->

<div class="selection" id="page-<?php echo $trw; ?>">
   <?php $tr = 1;
   foreach($this->destination as $key => $destination) : ?>

    <div class="row-fluid" id="spacing">

            <div class ="images span6" >

               <?php if ($destination['source'] != '') {

                ?>

                    <a class="zoom" href="<?php echo $this->imageUrl('/upload/poi/' . basename($destination['source'])) ?>">



                      <img src="<?php echo $this->imageUrl('timthumb.php?src=upload/culture/' . basename($destination['source']) . '&w=150&h=150&p=100') ?>"

                           alt="<?php echo $destination['poiName'] ?>" title="<?php echo $destination['poiName'] ?>" />

              <?php } else {

                ?>

                      <img src="<?php echo $this->imageUrl('/default.jpg'); ?>"

                           alt="<?php echo $destination['poiName'] ?>" title="no image for this destination" />

              <?php } ?>

              </a>
          </div>

            <div class="keterangan span18">
               <h3>

                        <a class="judul" href="<?php

                  echo $this->baseUrl('/culture/' .

                          $destination['poi_id'] . '/' .

                          $this->makeUrlFormat($destination['poiName']))

                  ?>">

                             <?php echo $destination['poiName'] ?>

                        </a>

              </h3>

<!-- 

                <p class="section-metadata">

                    <span class="date"><?php echo $this->newsMeta($news['publish_date']); ?></span>

                </p> -->



                <p>

                    <?php echo $this->truncate($destination['description'], 250) ?>

                </p>



                <span class="read-more-lb">

                    <?php

                            echo $this->partial('partials/read-more.phtml', array(


                                'class' => 's-btn s-btn-orange',

                                'controller' => $this->controller,

                                'id' => $destination['poi_id'],

                                'title' => $destination['poiName'],

                                'readMore' => 'Read More'

                            ));

                    ?>

                </span>
            </div>
        <div>
    </div>
</div>

    <!-- Paging Logic -->
    <?php if($key + 1 == $this->count): ?>
        </div>
    <?php elseif($key > 0 && $tr % 5 == 0): ?>
            <?php $trw++; ?>
            </div>
            <div class="selection" id="page-<?php echo $trw; ?>">
    <?php endif; ?>
    <?php $tr++; ?>
    <?php endforeach; ?>
    <!-- -->


<!-- view for pagination -->
<!-- <div class="paginate">
</div> -->
<!-- -->

<?php $this->placeholder('jsInline')->captureStart(); ?>
<script type="text/javascript">

    $(document).ready(function(){
        test(0);
    });

    function test(pageNumber)
    {
        if(pageNumber == '' || pageNumber ==  null || pageNumber == 0)
        {
            pageNumber = 1;
        }
      var page="#page-"+pageNumber;
      $('.selection').hide()
      $(page).show()

    }

    $(function() {
    $(".paginate").pagination({
        items: '<?php echo $this->count; ?>',
        itemsOnPage: 5,
        cssStyle: 'light-theme',
        onPageClick: function(pageNumber){test(pageNumber)}
    });
});
</script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>