<div class="section">
    <a name="firstsection"></a>
    <h2 class="section-title"><span>
    <?php if($this->langIId==1){
        $msgsort = 'SortBy:';
        $textnamesort = 'Name';
        $textfeaturedsort = 'Featured';
        $textprioritysort = 'Priority';
    }else {
        $msgsort = 'Diurut berdasarkan:';
        $textnamesort = 'Nama';
        $textfeaturedsort = ' Destinasi Utama ';
        $textprioritysort = 'Prioritas';
    }    ?>


    <?php if($this->showall): ?>
        <?php if($this->langIId==1){?>Destinations in Indonesia<?php } else { ?>Destinasi di Indonesia<?php } ?>
    <?php else:?>
        <?php echo $this->translate('destination_in_list'); ?>
    <?php endif;?>
    </span></h2>
    <?php if(count($this->destination)) :?>
        <?php echo $msgsort;?> <?php echo $this->columnSort($this->nameSort,
                                array(
                                      'param' => $this->sortBy,
                                      'title' => $textnamesort)); ?>
        <?php echo $this->columnSort($this->ratingSort,
                                array(
                                      'param' => $this->sortBy,
                                      'title' => 'Rating')); ?>
        <?php if($this->showall): ?>
            <a href="<?php echo $this->baseUrl('/destination/search/sortby/featured'); ?>"><?php echo $textfeaturedsort;?></a>
            <a href="<?php echo $this->baseUrl('/destination/search/sortby/priority'); ?>"><?php echo $textprioritysort;?></a>
        <?php endif; ?>
        <?php echo $this->render('destination/search-list.phtml'); ?>
    <?php else: ?>
        <b><?php echo $this->translate('destination_not_exist'); ?></b>
        <br /><br />
        <p><?php echo $this->translate('id_search_dest_again'); ?></p>
        <br />
        <form id="searchDestForm" action="<?php echo $this->baseUrl('/destination/' .
                         $this->action) ?>" method="POST" onsubmit="onSearchDestForm()">
            <input id="name" name="name" value="<?php echo $this->name ?>" type="text">
            <input value="<?php echo $this->translate('id_search_text'); ?>" class="button" type="submit">
         </form>
    <?php endif; ?>
</div>

<!-- Javascript -->
<?php $this->placeholder("jsInline")->captureStart() ?>
    <script type="text/javascript">
    function onSearchDestForm()
    {
        var searchName = $('#name').val();

        var currentAction = $('#searchDestForm').attr('action');
        $('#searchDestForm').attr('action', currentAction + '/name/' + searchName);
    }
    </script>
<?php $this->placeholder("jsInline")->captureEnd() ?>
