    <thead>
    	<tr class="tableNewsHeader">
                <th class="tableHeaderDefault" style="width: 200px;">Name</th>
                <th class="tableHeaderDefault" style="width: 180px;">Area</th>
                <th class="tableHeaderDefault" style="width: 250px;">Category</th>
                <th class="tableHeaderDefault" style="width: 120px;">Status</th>
                <th class="tableHeaderDefault">Indonesia</th>
        </tr>
    </thead>
