<div class="widget-wrap" id="facebook">       
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.async=true; js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=493949460635877";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <fb:like-box href="<?php echo FACEBOOK_PAGE_URL ?>" width="293" show_faces="true" stream="false" header="true"></fb:like-box>                     
</div>