<!--<div class="widget-wrap widget-shortcut">
  <a href="<?php echo $this->baseUrl('map') ?>"><h2 class="icon-map"><span><?php echo $this->translate('Culture Map') ?> &raquo;</span></h2></a>  
  <a href="<?php echo $this->baseUrl('video') ?>"><h2 class="icon-video"><span><?php echo $this->translate('Video Gallery') ?> &raquo;</span></h2></a>  
  <a href="<?php echo $this->baseUrl('chart') ?>"><h2 class="icon-statistics"><span><?php echo $this->translate('Culture Chart') ?> &raquo;</span></h2></a>  
</div>-->

<!--<div class="widget-wrap widget-shortcut">
    <a href="<?php echo $this->baseUrl('map') ?>">
        <div>
            <h2 class="target" style="float:left;">
                <span><?php echo $this->translate('Culture Map') ?></span>
            </h2>
            <img src="<?php echo $this->imageUrl('icons/compass.jpg') ;?>" alt="" />
        </div>
    </a>
    <a href=""></a>
    <a href=""></a>
</div>-->

<div class="widget-shortcut">
  <a href="<?php echo $this->baseUrl('map') ?>"><img src="<?php echo $this->imageUrl('icons/petabudaya.jpg'); ?>" alt="" /></a>  
  <a href="<?php echo $this->baseUrl('video') ?>"><img src="<?php echo $this->imageUrl('icons/galeribudaya.jpg'); ?>" alt="" /></a>  
  <a href="<?php echo $this->baseUrl('chart') ?>"><img src="<?php echo $this->imageUrl('icons/grafikbudaya.jpg'); ?>" alt="" /></a>  
</div>