<div class="widget-wrap" id="twitter">
<a class="twitter-timeline" href="https://twitter.com/budayasaya" data-widget-id="273304782976991233">Tweet oleh @budayasaya</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</script>
</div>