<?php $this->placeholder('styles')->captureStart(); ?>
<link href="<?php echo $this->scriptUrl('/styles/table-css.php'); ?>" rel="stylesheet" type="text/css" />
<?php $this->placeholder('styles')->captureEnd(); ?>

<!-- print out any message from create/saved page proccess-->
<?php
if (!empty($this->message)) {
  foreach ($this->message as $warn)
    echo $this->flashMessage($warn);
}
?>

<!-- print out any message from create/saved page proccess-->
<h2>Image Menu</h2>
<h3>Create, Update, or Delete from the list</h3>
<div class="table-container">
<br />
  <input type="button" class="btn radius" style="margin-bottom: 10px;" 
         value="+ Add Image" 
         onclick="window.location='<?php echo $this->rootUrl('admin/image/upload') ?>'"/>
  <br class="clearfloat"  />
  <?php echo $this->partial('image/filter-panel.phtml', array('alert' => $this->alert)) . "\n"; ?>
<?php echo $this->render('partial/page-filter.phtml'); ?>

  <!-- generating alert on filter selected -->
  <br class="clearfloat" />

  <br class="clearfloat"  />
  <?php if (count($this->paginator) > 0) : ?>
  <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination-control.phtml'); ?>
    <br class="clearfloat"  />

    <table style="width:100%;" cellspacing="0" class="table table-stripped table-bordered">
        <?php echo $this->partial('image/table-header.phtml') . "\n"; ?>
      <tbody>
        <?php $row_index = 0; ?>
  <?php echo $this->partialLoop('image/table-row.phtml', $this->paginator) . "\n"; ?>
      </tbody>
    </table>

    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination-control.phtml'); ?>
    <br class="clearfloat"  />
<?php endif; ?>
</div>

<div id="processLoader" class="hidden">
  <img src='<?php echo $this->imageUrl('ajax-loader-big.gif'); ?>'/>
</div>

<?php
$this->placeholder('jsInline')->captureStart();
?>

<script type="text/javascript">

  function deleteImage(gallery_id,obj)
  {
    if(confirm('Are you sure you want to delete this image?'))
    {
      tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
      $.ajax({
        type: "POST",
        url: "<?php echo $this->rootUrl() . '/admin/ajax/deleteimage'; ?>",
        data: {galleryid:gallery_id}, 
        success: function(data){
          obj.parents('tr.tableNewsData').remove(); 
          window.location.reload(true);
        }
      });    
    }
       
    $('.destination-box').autocomplete("<?php echo $this->rootUrl() . '/admin/ajax/poiautocomplete'; ?>",
    {
      minChars: 2,
      width: 180,
      selectFirst: false,
      loaderImage: "<?php echo $this->imageUrl('mini-loader.gif'); ?>"
    });
    
  }

  function hideAllFilter()
  {
    $('.name-box').hide();
    $('.poi-box').hide();
  }

  /*switch filter appearance*/
  function filterSwitch(value)
  {   
    switch(value)
    {
      case "0": hideAllFilter();
        break;
      case "1": hideAllFilter();
        $('.name-box').fadeIn('slow');
        $('.filter-btn').fadeIn('slow');
        break;
      case "2": hideAllFilter();
        $('.poi-box').fadeIn('slow');
        $('.filter-btn').fadeIn('slow');
        break;
    }
  }

  $(function(){
    $('.filter-panel').show();
        
    $('.highlightImage').lightBox();

    $('.poi-box').autocomplete("<?php echo $this->rootUrl() . '/admin/ajax/poiautocomplete'; ?>",
    {
      minChars: 2,
      width: 180,
      selectFirst: false,
      loaderImage: "<?php echo $this->imageUrl('mini-loader.gif'); ?>"
    });
  });

</script>

<?php $this->placeholder('jsInline')->captureEnd(); ?>