<div id="navigation">
  <ul class="mainnav">
    <li><a>Main Content</a>
      <ul class="subnav">
<!--                <li><a href="<?php echo $this->rootUrl('admin/activity'); ?>">Activity</a></li>-->
<!--                <li><a href="<?php echo $this->rootUrl('admin/article'); ?>">Attraction</a></li>-->
        <li><a href="<?php echo $this->rootUrl('admin/destination'); ?>">Destination</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/event'); ?>">Event</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/highlight'); ?>">Highlight</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/news'); ?>">News</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/region'); ?>">Region</a></li>
<!--                <li><a href="<?php echo $this->rootUrl('admin/tourismoperator'); ?>">Tourism Operator</a></li>-->
<!--                <li><a href="<?php echo $this->rootUrl('admin/photoessay'); ?>">Photo Essay</a></li>-->
      </ul>
    </li>
    <li><a>Indonesian Content</a>
      <ul class="subnav">
<!--                <li><a href="<?php echo $this->rootUrl('admin/activityindo'); ?>">Activity</a></li>-->
<!--                <li><a href="<?php echo $this->rootUrl('admin/articleindo'); ?>">Attraction</a></li>-->
        <li><a href="<?php echo $this->rootUrl('admin/destinationindo'); ?>">Destination</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/eventindo'); ?>">Event</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/highlightindo'); ?>">Highlight</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/newsindo'); ?>">News</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/regionindo'); ?>">Region</a></li>
<!--                <li><a href="<?php echo $this->rootUrl('admin/tourismoperatorindo'); ?>">Tourism Operator</a></li>-->
      </ul>
    </li>
    <li><a>Complementary</a>
      <ul class="subnav">
<!--                <li><a href="<?php echo $this->rootUrl('admin/airlines'); ?>">Airlines</a></li>-->
<!--                <li><a href="<?php echo $this->rootUrl('admin/airlinesindo'); ?>">Airlines Indo</a></li>-->
        <li><a href="<?php echo $this->rootUrl('admin/comment'); ?>">Comment</a></li>
<!--                <li><a href="<?php echo $this->rootUrl('admin/materialpromotion'); ?>">Promotional Materials</a></li>-->
<!--                <li><a href="<?php echo $this->rootUrl('admin/materialpromotionindo'); ?>">Promotional Materials Indo</a></li>-->
        <li><a href="<?php echo $this->rootUrl('admin/page'); ?>">Static Content (Page)</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/pageindo'); ?>">Static Content Indo</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/relatedlinks'); ?>">Related Links</a></li>
        <li><a href="<?php echo $this->rootUrl('admin/relatedlinksindo'); ?>">Related Links Indo</a></li>
<!--                <li><a href="<?php echo $this->rootUrl('admin/review'); ?>">Review</a></li>-->
<!--                <li><a href="<?php echo $this->rootUrl('admin/tourpackage'); ?>">Tour Packages</a></li>-->
<!--                <li><a href="<?php echo $this->rootUrl('admin/tourpackageindo'); ?>">Tour Packages Indo</a></li>-->
<!--                <li><a href="<?php echo $this->rootUrl('admin/vito'); ?>">Vito</a></li>-->
<!--                <li><a href="<?php echo $this->rootUrl('admin/vitoindo'); ?>">Vito Indo</a></li>-->
      </ul>
    </li>
    <li style="width:155px"><a>System</a>
      <ul class="subnav">
        <li style="width:150px;"><a href="<?php echo $this->rootUrl('admin/account'); ?>">Admin Account</a></li>
        <li style="width:150px;"><a href="<?php echo $this->rootUrl('admin/log'); ?>">Log</a></li>
        <li style="width:150px;"><a href="<?php echo $this->rootUrl('admin/role'); ?>">Role</a></li>
        <li style="width:150px;"><a href="<?php echo $this->rootUrl('admin/user'); ?>">User</a></li>
      </ul>
    </li>
    <li style="width:100px;"><a>Media</a>
      <ul class="subnav">
        <li style="width:95px;"><a href="<?php echo $this->rootUrl('admin/image'); ?>">Image</a></li>
      </ul>
    </li>
    <li><a>Communication</a>
      <ul class="subnav">
        <li><a href="<?php echo $this->rootUrl('admin/contact'); ?>">Contact</a></li>
      </ul>
    </li>
  </ul>
</div>