<?php
if(APPLICATION_ENV == 'development' || APPLICATION_ENV == 'staging') {
    echo $this->exception ;
    echo $this->request;
}
?>

<div id="error-box">
    <p class="center">        
        <?php if ($this->err == 1): // untuk sementara ini file 404-nya sama untuk bhs indonesia dan inggris ?>        
            <img src="<?php echo $this->imageUrl('/frontend/error-404.jpg') ?>"/>
        <?php else: ?>        
            <img src="<?php echo $this->imageUrl('/frontend/error-404.jpg') ?>"/>
        <?php endif; ?>
    </p>
</div>