<div class="filter-panel hidden">
    
    <h4 style="margin-top: 10px;"><label for="filterPage">Filter:</label></h4>
    
    <form action="<?php echo $this->currentUrl(); ?>" method="post">
        <select class="filter-box" name="filterPage" id="filterPage"
                onchange="filterSwitch(this.value);">
            <option value="0">Show All</option>
            <option value="1">Name</option>
        </select>
        
        <select class="area-box hidden" name="filterarea">
            <?php foreach($this->island as $island_data): ?>
                <optgroup label="<?php echo $island_data['name']; ?>">
                    <?php $province_list = $this->ProvinceList($island_data['id']); ?>
                        <?php foreach($province_list as $province_id => $province_name) : ?>
                            <option value="<?php echo $province_id; ?>">
                                <?php echo $province_name; ?>
                            </option>
                        <?php endforeach; ?>
                </optgroup>
            <?php endforeach; ?>
        </select>
        
        <input type="text" class="name-box mediumele hidden" name="filtertitle"/>
        
        <input type="submit" value="Go" class="btn radius" />
        
    </form>                    
</div>