<div class="row-fluid">
  <form action="" method="post" enctype="multipart/form-data">
    <div class="row-fluid">
      <div class="control-group">
        <label for="name">Nama Sosok</label>
        <div class="controls">
          <?php echo $this->form->name; ?>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span8">
        <div class="control-group">
          <div class="controls">
            <?php echo $this->form->description; ?>
          </div>
        </div>
      </div>
      <div class="span4 well">
        <div class="control-group">
          <div class="controls">
            <div class="fileupload fileupload-new" data-provides="fileupload">
              <div class="fileupload-new thumbnail" style="width:200px;height:150px">
                <?php if (isset($this->image)): ?>
                  <img src="<?php echo $this->imageUrl("upload/figure/{$this->image}"); ?>" alt="" />
                <?php else: ?>
                  <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=200+x+150" alt="" />
                <?php endif; ?>
              </div>
              <div class="fileupload-preview fileupload-exists thumbnail" 
                   style="width: 200px;height: 150px;">
              </div>
              <div>
                <?php
                $disabled = '';
                if ($this->form->image->getAttrib('disabled') == true) $disabled = 'disabled';
                ?>
                <div class="btn btn-file <?php echo $disabled ?>">
                  <span class="fileupload-new">Pilih Gambar</span>
                  <span class="fileupload-exists">Ganti</span>
                  <?php echo $this->form->image; ?>
                </div>
                <a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Hapus</a>
              </div>
            </div>
            <ul class="errors">
              <?php foreach ($this->form->image->getMessages() as $key => $message): ?>
                <li><?php echo $message; ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <?php echo $this->form->draft; ?>
      <?php echo $this->form->submit; ?>
    </div>
  </form>
</div>

<?php echo $this->render('partial/tinyMCE.phtml'); ?>