<div class="section">
    <h2 class="section-title">
        <span><?php echo $this->escape($this->article['title']) ?></span>
    </h2>    
    <p>
        <img src="<?php echo $this->mediaUrl('images/upload/article/' . $this->article['main_image']) ?>" class="alignleft" alt="" />
        <?php echo $this->article['content'] ?>
    </p>
    <?php echo $this->render('partials/socialnetwork.phtml') ?>
</div>