<?php 
    $this->placeholder('jsInline')->captureStart();
?>  

<script type="text/javascript">
$(function(){
        $("#tourismop input").blur(function(){
            $("#tourismop").validate().element($(this));
        });
        
        $("#tourismop").validate({
            meta: "validate",
            rules : {
                        TourismOperatorEmail:{
                            email: true
                        },
                        TourismOperatorWebsite:{
                            url: true
                        },
                        TourismOperatorLangName: "required",
                        TourismOperatorRegion: "required",
                    },
            messages : {
                         TourismOperatorLangName: "Please enter a name!",
                         TourismOperatorRegion: "Please enter a country!",
                         TourismOperatorWebsite:{
                            url: "Please enter a valid URL, make sure theres 'http://' in front of your URL"
                         },
                         TourismOperatorEmail:{
                            email: "Please enter a valid email address"
                         }
                      } 
        });
});
</script>
<?php $this->placeholder('jsInline')->captureEnd();?>  