<form name="newsForm" id="newsForm"  method="post" class="form-horizontal well" enctype="multipart/form-data" >
  <?php echo $this->form->newsStatus; ?>
  <?php echo $this->form->PoiCounter; ?>

  <fieldset>
    <p class="f_legend">News Detail</p>
    <div class="control-group">
      <label class="control-label" for="newsTitle">News Title</label>
      <div class="controls">
        <?php echo html_entity_decode($this->form->newsTitle); ?>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="newsContent">Content</label>
      <div class="controls">
        <?php echo $this->form->newsContent; ?>
      </div>
    </div>
  </fieldset>

  <?php if ($this->langId != 2): ?>
    <fieldset>
      <p class="f_legend">News Information</p>
      <div class="control-group">
        <label for="newsPoi" class="control-label">Add Related Culture Item</label>
        <div class="controls">
          <?php echo $this->form->newsPoi; ?>
          <span class="help-block">Type and Choose Culture Item from Autocompletes</span>
        </div>
        <span class="ajax-loader"></span><span class="mini-ajaxloader"></span>
        <label class="control-label" for="">Related Culture Item</label>
        <div class="controls">
          <table class="margin_r" id="poiContainer" cellpadding="0"></table>
        </div>
      </div>


      <div class="control-group">
        <label for="newsImage" class="control-label">Add News Image</label>
        <div class="controls">
          <?php echo $this->form->image; ?>
          <br /><br />
          <?php if ($this->picture != null): ?>
            <?php
            $src      = "upload/news/$this->picture";
            $timthumb = $this->imageUrl("timthumb.php?src={$src}&w=300&h=150&q=100")
            ?>
            <img src="<?php echo $timthumb; ?>" alt="" />
          <?php endif; ?>
        </div>
      </div>


      <div class="control-group">
        <label for="newsPublishDate" class="control-label">Publish Date</label>
        <div class="controls">
          <td><?php echo $this->form->newsPublishDate; ?></td>
        </div>
      </div>
    </fieldset>


    <fieldset>
      <legend class="f_legend">Related Articles</legend>
      <div class="control-group">
        <div class="controls">
          <?php if ($this->edit == 1): ?>
            <input type="hidden" size=1 id="counterRelated" name="counterRelated" value="<?php echo count($this->ralated_news); ?>" />
            <input type="hidden" size=1 id="counterDel" name="counterDel" value="0" />


            <table id="tbrelated-article">
              <tr id="tbrelated-header" style="display:none"></tr>
              <?php if (sizeof($this->ralated_news)): ?>
                <?php
                $counter = 1;
                ?>
                <?php foreach ($this->ralated_news as $ralated_news): ?>
                  <tr>
                    <td>
                      <input type="text" id="relatedLabel<?php echo $ralated_news->related_id; ?>" class="mediumele valid" name="label<?php echo $counter; ?>" value="<?php echo $ralated_news->label; ?>" />
                    </td>
                    <td>
                      <input type="text" id="relatedLink<?php echo $ralated_news->related_id; ?>" class="mediumele valid" name="link<?php echo $counter; ?>" value="<?php echo $ralated_news->link; ?>" />
                    </td>
                    <td>
                      <div class="general-remove" id="<?php echo $ralated_news->related_id; ?>" onclick="delRelatedArticleEdit($(this));">Delete</div>
                    </td>
                  </tr>
                  <?php $counter++; ?>
                <?php endforeach; ?>
              <?php endif; ?>

            </table>
            <div id="tmpDelete">
              <?php
              /*
                div ini digunakan untuk menampung data related article yang di delete
                (temporary_field), bentuknya texbox yang di hidden
                yang akan dikirimkan ke controller
               */
              ?>
            </div>

          <?php else: ?>
            <table id="tbrelated-article">
              <tr id="tbrelated-header" style="display:none"></tr>
            </table>
            <input type="hidden" id="counterRelated" name="counterRelated" value="0" />
          <?php endif; ?>

          <table>
            <tr>
              <td>
                <input class="btn radius valid" type="button" onclick="relatedArticle();" value="+ Related Article" style="margin-bottom:10px;">
              </td>
            </tr>
          </table>
        </div>
      </div>
    </fieldset>
  <?php endif; ?>


  <div class="form-actions">
    <?php echo $this->form->draft; ?>
    <?php echo $this->form->submit; ?>
  </div>


</form>
<?php echo $this->render('partial/upload-image-dialog.phtml'); ?>

