<?php
if (!empty($this->message)) {
  foreach ($this->message as $warn)
    echo $this->flashMessage($warn);
}
?>

<h3>News Menu</h3>
<h5 class="wide">Create, Update, or Delete from the list</h5>

<div class="table-container">
  <br />
  <input type="button" class="btn radius" style="margin-bottom: 10px;" 
         value="+ Add News" onclick="window.location='<?php echo $this->rootUrl('admin/news/create'); ?>'"/>

  <br class="clearfloat" />

  <?php $panel_data = array('year'  => $this->year_list, 'alert' => $this->alert); ?>
  <?php echo $this->partial('news/filter-panel.phtml', $panel_data) . "\n"; ?>
  <?php echo $this->render('partial/page-filter.phtml'); ?>


  <?php if (count($this->paginator) > 0) : ?>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination-control.phtml'); ?>
    <table class="table table-striped table-bordered table-condensed">
      <!--            menampilkan header news-->
      <col width="65% "/>
      <col widht="15%"/>
      <col width="20%"/>
      <?php echo $this->partial('news/table-header.phtml'); ?>
      <tbody>
        <?php $row_index = 0; ?>
        <?php echo $this->partialLoop('news/table-row.phtml', $this->paginator); ?>
      </tbody>
    </table>

    <!-- print out the pagination control at the bottom of the table -->
    <!--        menampilkan pagination bawah-->
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination-control.phtml');
    ?>

    <br class="clearfloat" />
  <?php endif; ?>	
</div>

<div id="processLoader" class="hidden">
  <img src='<?php echo $this->rootUrl('/media/images/ajax-loader-big.gif') ?>'/>
</div>

<!-- start capturing the javascript -->
<?php
$this->placeholder('jsInline')->captureStart();
?>

<script type="text/javascript">
	
  /**
   * IS: -
   * FS: Semua filter box tidak tertampil
   * Desc: Menyembunyikan seluruh filter
   */
  function hideAllFilter()
  {
    $('.poi-box').hide();
    $('.language-box').hide();
    $('.title-box').hide();
    $('.year-box').hide();
    $('.month-box').hide();
    $('.status-box').hide();
  }
    
  /**
   * IS: Tertampil hanya filter default 'Show All'
   * FS: Tertampil filter box tambahan sesuai pilihan
   * Desc: Mengganti tampilan filter
   */
  function filterSwitch(value)
  {   
    switch(value)
    {
      case "0": hideAllFilter();
        break;
      case "1": hideAllFilter();
        $('.title-box').fadeIn('slow');
        break;
      case "2": hideAllFilter();
        $('.poi-box').fadeIn('slow');
        break;
      case "3": hideAllFilter();
        $('.year-box').fadeIn('slow');
        $('.month-box').fadeIn('slow');
        break;
      case "4": hideAllFilter();
        $('.status-box').fadeIn('slow');
        break;
    }
  }
    
  /**
   * IS: News ada
   * FS: News tidak ada, dan dihapus dari basis data
   * Desc: Menghapus news, 
   *       send request via ajax for deleting the news into the table
   */
  function deleteNews(news_id)
  {
    if (confirm('Do you really want to archive this news?'))
    {
      tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
      $.ajax(
      {
        type: "POST",
        url: "<?php echo $this->rootUrl('/admin/ajax/deletenews'); ?>",
        data: {newsid:news_id}, 
        success: function(data)
        {
          window.location.reload(true);
        },
        error: function()
        {
          alert('Error occured, please report this to the developer');
        }
      });    
    }        
  }

  function deleteNews2(news_id)
  {
    if (confirm('Do you really want to archive this English Translation news?'))
    {
      tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
      $.ajax(
      {
        type: "POST",
        url: "<?php echo $this->rootUrl('/admin/ajax/deletenews2'); ?>",
        data: {newsid:news_id},
        success: function(data)
        {
          window.location.reload(true);
        },
        error: function()
        {
          alert('Error occured, please report this to the developer');
        }
      });
    }
  }

  /**
   * IS: Status news publish atau draft
   * FS: Status news berubah dari publish menjadi draft atau sebaliknya
   * Desc: Mengganti status news menjadi publish atau draft
   */
  function changeNewsStatus(news_id, obj, status)
  {
    if (confirm('Do you really want to change this news status?'))
    {
      tb_show("", 
      "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", 
      "");
      $.ajax(
      {
        type: "POST",
        url: 
          "<?php echo $this->rootUrl('/admin/ajax/hideshownews'); ?>",
        data: {newsid:news_id}, 
        success: function(data)
        {
          obj.html(data);
          tb_remove();
          window.location.reload(true);
        },
        error: function()
        {
          alert('Error Occured, please report this to the developer');
        }
      });
    }        
  }
    
  $(function(){
    hideAllFilter();    
    $('.poi-box').autocomplete("<?php echo $this->rootUrl('/admin/ajax/poiautocomplete'); ?>",
    {
      minChars: 2,
      width: 180,
      selectFirst: false,
      loaderImage: "<?php echo $this->rootUrl('/media/images/mini-loader.gif') ?>"
    });
  });
</script>

<?php $this->placeholder('jsInline')->captureEnd(); ?>