<?php $this->placeholder('styles')->captureStart(); ?>
<link href="<?php echo $this->scriptUrl('/styles/table-css.php'); ?>" rel="stylesheet" type="text/css" />
<?php $this->placeholder('styles')->captureEnd(); ?>
<?php 
    $pagination_control = $this->paginationControl($this->contact,'sliding'
            ,'partial/pagination_control.phtml');

?>

<!-- print out any message from create/saved page proccess -->
<?php 
if (!empty($this->message))
{
    foreach ($this->message as $warn) echo $this->flashMessage($warn);
}
?>

<form action="" method="post">
    <div class="row-fluid" style="margin-bottom: 25px">
        <div class="pull-left">
            <h3 style="display: inline">Kontak</h3>
        </div>
        <div class="pull-right">
            Tampilkan
            <?php echo $this->formSelect('filter[row]',$this->filter['row'],
                    array('style' => 'width: 50px'),
                    array(
                        5 => 5,
                        10 => 10,
                        25 => 25,
                        100 => 100
                    )); ?>
            <button class="btn" name="action" value="filter">
                Setel
            </button>
        </div>
        
        </div>
        <div class="row-fluid">
            <div class="row-fluid">
                <div class="pull-left">
                    <button class="btn btn-mini"
                            name="action"
                            value="delete"
                            onclick="if(!confirm('Apakah anda yakin ingin menghapus ini?'))
                            return false">
                        <i class="icon-trash"></i>
                    </button>
                    <button class="btn btn-mini"
                            name="action"
                            value="filter">
                        <i class="icon-filter"></i>Gunakan Filter
                    </button>
                    <button class="btn btn-mini"
                            name="action"
                            value="reset">
                        Atur Ulang Filter
                    </button>
                </div>
                <div class="pull-right">
                    <?php echo $pagination_control; ?>
                </div>
            </div>
            <div class="row-fluid">
                <table class="table table-striped table-condensed" id="table-contact">
                    <col width="5%"/>
                    <col width="10%"/>
                    <col width="15%"/>
                    <col width="15%"/>
                    <col width="25%"/>
                    <col width="25%"/>
                    <col width="5%"/>
                    <thead>
                        <tr>
                            <th>
                                <input type="checkbox" name="" id=""
                                       onchange="if($(this).attr('checked'))
                                       $('#table-contact tbody input:checkbox')
                                .removeAttr('checked',true);
                                else
                                $('#table-contact tbody input:checkbox')
                                .removeAttr('checked');"/>
                            </th>
                            <th>Tanggal</th>
                            <th>Nama</th>
                            <th>Email</th>
                            <th>Subjek</th>
                            <th>Keterangan</th>
                            <th></th>
                        </tr>
                        <tr>
                            <th></th>
                            <th></th>
                            <th>
                                <?php 
                                    echo $this->formText('filter[name]',
                                            $this->filter['name'],
                                            array('class' => 'span12',
                                                'style' => 'margin-bottom:5px',
                                                'placeholder' => 'Cari Nama...'));
                                ?>
                            </th>
                            <th></th>
                            <th>
                                <?php echo $this->formSelect('filter[subject]',
                                        $this->filter['subject'],
                                        array('class' => 'span12'),
                                        array(
                                            null => 'Tampilkan Semua',
                                            1 => 'Pertanyaan Informasi Kebudayaan',
                                            3 => 'Pendaftaran Kontributor',
                                            4 => 'Respon / Komentar Situs Ini',
                                            5 => 'Lain-lain'
                                        )); ?>
                            </th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($this->contact as $index => $contact): ?>
                        <tr>
                            <td>
                                <input type="checkbox"
                                       name="contact[]"
                                       value="<?php echo $contact->contact_id; ?>"/>
                            </td>
                            <td>
                                <?php echo $contact->date; ?>
                            </td>
                            <td>
                                <a href="<?php echo $this->rootUrl(); ?>/admin/contact/detail/id/<?php echo $contact->contact_id; ?>">
                                <?php echo $contact->name; ?>
                                </a>
                            </td>
                            <td>
                                <?php echo $contact->email; ?>
                            </td>
                            <td>
                                
                                <?php switch ($contact->subject)
                                {
                                    case '1':
                                        $contact->subject = 'Pertanyaan Informasi Kebudayaan';
                                        break;
                                    case '3':
                                        $contact->subject = 'Pendaftaran Kontributor';
                                        break;
                                    case '4':
                                        $contact->subject = 'Respon / Komentar Situs Ini';
                                        break;
                                    case '5':
                                        $contact->subject = 'Lain-Lain';
                                        break;
                                } 
                                ?>
                                <?php echo $contact->subject; ?>
                            </td>
                            <td>
                                <?php switch ($contact->status)
                                {
                                    case '0':
                                        $contact->status = 'Belum Dibalas';
                                        break;
                                    case '1':
                                        $contact->status = 'Balasan Menunggu Persetujuan';
                                }
                                ?>
                                <?php echo $contact->status; ?>
                            </td>
                            <td>
                                <a title="Hapus" onclick="if(!confirm('Apakah anda yakin ingin '+
                                'menghapus kontak ini?')) return false" href="<?php
                                    echo $this->url(array(
                                        'action' => 'delete',
                                        'id'     => $this->highlight_id
                                    ));
                                    ?>">
                                <i class="icon-trash"></i>
                                </a>
                                
                                <a title="Kirim Balasan" onclick="if(!confirm('Apakah anda yakin ingin '+
                                'menghapus kegiatan ini?')) return false" href="<?php
                                    echo $this->url(array(
                                        'action' => 'delete',
                                        'id'     => $this->highlight_id
                                    ));
                                    ?>">
                                    <i class="icon-edit"></i>
                                </a>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>    
    </form>
<?php 
$this->placeholder('jsInline')->captureStart();
?>
<script type="text/javascript">
    function deleteContact(contact_id)
    {
        if(confirm('Are you sure you want to delete this contact message?'))
        {
            tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
            $.ajax({
                type: "POST",
                url: "<?php echo $this->rootUrl().'/admin/ajax/deletecontact'; ?>",
                data: {contact_id:contact_id},
                success: function(data){
                    window.location.reload(true);
                },
                error: function(){alert('Error Occured, please report this to the developer');}
            });        
        }
    }

    function updateflag(contact_id){

        tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->rootUrl().'/admin/ajax/updateflagcontact'; ?>",
            data: {contact_id:contact_id},
            success: function(data){
                window.location.reload(true);
            },
            error: function(){alert('Error Occured, please report this to the developer');}
        });

    }

    function updateflag1(contact_id){

        tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->rootUrl().'/admin/ajax/updateflagcontact1'; ?>",
            data: {contact_id:contact_id},
            success: function(data){
                window.location.reload(true);
            },
            error: function(){alert('Error Occured, please report this to the developer');}
        });

    }

    function filterSwitch(value)
    {

        switch(value)
        {
            case "0": hideAllFilter();
                break;
            case "1": hideAllFilter();
                $('.name-box').fadeIn('slow');
                $('.filter-btn').fadeIn('slow');
                break;
            case "2": hideAllFilter();
                $('.status-box').fadeIn('slow');
                $('.filter-btn').fadeIn('slow');
                break;
            case "3": hideAllFilter();
                $('.subject-box').fadeIn('slow');
                $('.filter-btn').fadeIn('slow');
                break;
            case "4": hideAllFilter();
                $('.flag-box').fadeIn('slow');
                $('.filter-btn').fadeIn('slow');
                break;
            case "5": hideAllFilter();
                $('.country').fadeIn('slow');
                $('.filter-btn').fadeIn('slow');
                break;
        }
    }

    function hideAllFilter()
    {
        $('.name-box').hide();
        $('.status-box').hide();
        $('.subject-box').hide();
        $('.flag-box').hide();
        $('.country').hide();
    }

    function getAllCheckBoxes(elform, elname) {
        var hasil = Array();
        var n = 0;
        for (var i=0; i<elform.elements.length; i++) {
            if (elform.elements[i].type == 'checkbox' && elform.elements[i].name == elname) {
                hasil[n++] = elform.elements[i];
            }
        }
        return hasil;
    }

    var checkedAll = false;
    var chk = getAllCheckBoxes(document.contact, 'contact_item[]');

    function checkBoxAll(){
        if (!checkedAll) {
            checkedAll = true;
            for (i = 0; i < chk.length; i++)
                chk[i].checked = true;
        } else {
            checkedAll = false;
            for (i = 0; i < chk.length; i++)
                chk[i].checked = false;
        }
    }

    $(function()
    {
        $('.filter-panel').show();
    });

</script>
<script type="text/javascript">
    <!--

    function doSubmit(action) {
        var eform = document.contact;
        for (i = 0; i < eform.elements.length; i++){
            if (eform.elements[i].type == 'checkbox')
                if(eform.elements[i].checked){
                    switch (action) {
                        case 'delete_selected':
                            if (confirm("Ini Akan Menghapus Beberapa Email,Lanjutkan? ")) {
                                eform.actionnya.value = 'delete_selected';
                                eform.submit();
                            }
                            break;
                        case 'toggle_flag_selected':
                            eform.actionnya.value = 'toggle_flag_selected';
                            eform.submit();
                            break;
                        case 'flag_selected':
                            eform.actionnya.value = 'flag_selected';
                            eform.submit();
                            break;
                        case 'unflag_selected':
                            eform.actionnya.value = 'unflag_selected';
                            eform.submit();
                            break;
                        default:
                        //do nothing
                }
        }
    }

}

</script>

<?php $this->placeholder('jsInline')->captureEnd(); ?>