<?php
if (!empty($this->message)) {
  foreach ($this->message as $warn)
    echo $this->flashMessage($warn);
}
?>

<h3>Article Menu</h3>
<h5>Create, Update, or Delete from the list</h5>
<br />
<div class="table-container">

  <input type="button" class="btn radius" style="margin-bottom:10px;" value="+ Add Article" onclick="window.location='<?php echo $this->rootUrl('admin/article/create'); ?>'"/>
  <br class="clearfloat"  />
  <?php echo $this->partial('article/filter-panel.phtml', array('alert' => $this->alert)) . "\n"; ?>
  <?php echo $this->render('partial/page-filter.phtml'); ?>

  <?php if (count($this->paginator) > 0) : ?>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination-control.phtml'); ?>
    <table class="table table-striped table-bordered table-condensed">
      <col width="60%" />
      <col width="20%" />
      <col width="20%" />
      <?php echo $this->partial('article/table-header.phtml') . "\n"; ?>
      <tbody>
        <?php $row_index = 0; ?>                        
        <?php echo $this->partialLoop('article/table-row.phtml', $this->paginator) . "\n"; ?>
      </tbody>
    </table>

    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'partial/pagination-control.phtml'); ?>
    <br class="clearfloat"  />
  <?php endif; ?>
  <br class="clearfloat"  />
</div>

<div id="processLoader" class="hidden">
  <img src='<?php echo $this->imageUrl('ajax-loader-big.gif'); ?>'/>
</div>

<?php
$this->placeholder('jsInline')->captureStart();
?>
<script type="text/javascript">
  function hideAllFilter()
  {
    $('.title-box').hide();
    $('.poi-box').hide();
  }
        
  function filterSwitch(value)
  {   
    switch(value)
    {
      case "0": hideAllFilter();
        break;  
      case "1": hideAllFilter();
        $('.title-box').fadeIn('slow');
        $('.filter-btn').fadeIn('slow');
        break;  
      case "2": hideAllFilter();
        $('.poi-box').fadeIn('slow');
        $('.filter-btn').fadeIn('slow');
        break;
    }
  }        
    
  function DeleteArticle(article_id,obj)
  {   
    if(confirm('Do you want to delete this attraction?'))
    {
      tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
      $.ajax({
        type: "POST",
        url: "<?php echo $this->rootUrl() . '/admin/ajax/deletearticle'; ?>",
        data: {articleid:article_id}, 
        success: function(data){
          obj.parents('tr.tableDataDefault').remove();
          window.location.reload(true);
        }});            
    }
  }

  function DeleteArticle2(article_id,obj)
  {
    if(confirm('Do you want to delete this Indonesian Translation attraction?'))
    {
      tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
      $.ajax({
        type: "POST",
        url: "<?php echo $this->rootUrl() . '/admin/ajax/deletearticle2'; ?>",
        data: {articleid:article_id},
        success: function(data){
          obj.parents('tr.tableDataDefault').remove();
          window.location.reload(true);
        }});
    }
  }
    
  function changeArticleStatus(id,obj,status)
  {
    if(confirm('Do you want to change this attraction status?'))
    {
      tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
      $.ajax({
        type: "POST",
        url: "<?php echo $this->rootUrl() . '/admin/ajax/hideshowarticle'; ?>",
        data: {articleid:id},
        success: function(data){
          if(data == '1'){obj.html('published');}
          else if(data == '0'){obj.html('draft');}
          tb_remove();
          window.location.reload(true);
        }});
    }
  }
    
  $(function(){
    $('.filter-panel').show();
    $('.poi-box').autocomplete("<?php echo $this->rootUrl() . '/admin/ajax/poiautocomplete'; ?>",
    {
      minChars: 2,
      width: 160,
      selectFirst: false,
      loaderImage: "<?php echo $this->imageUrl('mini-loader.gif'); ?>"
    });
  });
</script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>    