
<?php $this->placeholder('jsInline')->captureStart(); ?>

<script type="text/javascript">

  function checkpoi(poi_name)
  {
    $('.ajax-loader').html("<img src='<?php echo $this->rootUrl('/media/images/mini-loader.gif'); ?>'/>");
    $('#ImagePoi').attr('disabled',true);
    $('.general-button').attr('disabled',true);
    $.ajax({
      type: "POST",
      url: "<?php echo $this->rootUrl() . '/admin/ajax/checkpoiname'; ?>",
      data: {poiname:poi_name},
      success: function(data){
        if(data!='error'){
          registerPoi(poi_name,data);
        }
        else{alert('No Destination with name "'+poi_name+'" found! Please Check Your Entry!');}
      }
    });
  }

  function registerPoi(poi_name,data)
  {
    html = "<div id='manipulation'><span id='poiname'>"+poi_name+"</span><span onclick='removePoi($(this));' id='removepoi'>edit Poi</span><input name='poivalue' type='hidden' value='"+data+"'></div>";
    $('.general-button').removeAttr('disabled');
    $('.ajax-loader').empty();
    $('#ImagePoi').hide();
    $('#ImagePoi').val('');
    $('td.poicontainer').append(html);
    $('.ImagePoi').removeAttr('disabled');
  }

</script>

<style>
  #poiname{color:black; font-weight: bolder;}
  #removepoi{margin-left: 5px; color:red; font-weight: bold;}
  #removepoi:hover{color:black; cursor: pointer;}
</style>

<script type="text/javascript" >
  function removePoi(obj)
  {
    obj.parent().remove();
    $('#ImagePoi').removeAttr('disabled');
    $('#ImagePoi').show();
  }
</script>

<script type="text/javascript">

  var optlanguage = "<?php echo $this->rootUrl() . '/admin/ajax/poiautocomplete'; ?>";

  $(function() {

    $('#language-choice').change(function(){
      $('#ImagePoi').setOptions({
        extraParams : {'languageID' : $('#language-choice').val()}
      });	
    });

    $("#imageForm").validate({
      meta: "validate",
      rules : {
<?php if (!$this->state_edit) : ?>
                              ImageUpload:{
                                required:true
                              },
<?php endif; ?>
                            ImageName:{
                              required:true
                            }
                          },
                          messages : {
                            ImageName : "The image name cannot be empty!"
                          }
                        });

<?php if ($this->state_edit): ?>
  <?php if ($this->poi_id > 0): ?>
            $('#ImagePoi').hide();
  <?php endif; ?>
<?php endif; ?>

    $('#ImagePoi').autocomplete(optlanguage,
    {
      minChars: 2,
      width: 160,
      selectFirst: false,
      loaderImage: "<?php echo $this->rootUrl('/media/images/mini-loader.gif'); ?>",
      extraParams: {'languageID' : $('#language-choice').val()}
    });
    $("#ImagePoi").result(function(event, data, formatted) {
      if (data){checkpoi(data);}
    });
  });
</script>

<?php $this->placeholder('jsInline')->captureEnd(); ?>