    <!--tab-->
    <div id="block-tab">
        <div id="tab1">
            <div class="tab-left <?php echo ($this->staticType == 'glance')? 'current' : 'active'?>"></div>
            <div class="tab-center <?php echo ($this->staticType == 'glance')? 'current' : 'active'?>">
                 <!--class="active"-->
                <a href="<?php echo $this->baseUrl('discover-indonesia#first');?>">
                    <span class="href-nostyle"><?php echo $this->translate('id_static_glance') ?></span>
                </a>
            </div>
            <div class="tab-right <?php echo ($this->staticType == 'glance')? 'current' : 'active'?>"></div>
        </div>

        <div id="tab2">
            <div class="tab-left <?php echo ($this->staticType == 'list')? 'current' : 'active'?>"></div>
            <div class="tab-center <?php echo ($this->staticType == 'list')? 'current' : 'active'?>">
                <a href="<?php echo $this->baseUrl('discover-indonesia/region-list#first');?>">
                    <span class="href-nostyle"><?php echo $this->translate('id_static_list') ?></span>
                </a>
            </div>
            <div class="tab-right <?php echo ($this->staticType == 'list')? 'current' : 'active'?>"></div>
        </div>

        <div id="tab3">
            <div class="tab-left <?php echo ($this->staticType == 'history')? 'current' : 'active'?>"></div>
            <div class="tab-center <?php echo ($this->staticType == 'history')? 'current' : 'active'?>">
                <a href="<?php echo $this->baseUrl('discover-indonesia/history#first') ?>">
                    <span class="href-nostyle"><?php echo $this->translate('id_static_history') ?></span>
                </a>
            </div>
            <div class="tab-right <?php echo ($this->staticType == 'history')? 'current' : 'active'?>"></div>
        </div>

        <div id="tab4">
            <div class="tab-left <?php echo ($this->staticType == 'language')? 'current' : 'active'?>"></div>
            <div class="tab-center <?php echo ($this->staticType == 'language')? 'current' : 'active'?>">
                <a href="<?php echo $this->baseUrl('discover-indonesia/language#first'); ?>">
                    <span class="href-nostyle"><?php echo $this->translate('id_static_language') ?></span>
                </a>
            </div>
            <div class="tab-right <?php echo ($this->staticType == 'language')? 'current' : 'active'?>"></div>
        </div>

        <div id="tab5">
            <div class="tab-left <?php echo ($this->staticType == 'florafauna')? 'current' : 'active'?>"></div>
            <div class="tab-center <?php echo ($this->staticType == 'florafauna')? 'current' : 'active'?>">
                <a href="<?php echo $this->baseUrl('discover-indonesia/florafauna') ?>">
                    <span class="href-nostyle"><?php echo $this->translate('id_static_florafauna') ?></span>
                </a>
            </div>
            <div class="tab-right <?php echo ($this->staticType == 'florafauna')? 'current' : 'active'?>"></div>
        </div>

        <div id="tab6">
            <div class="tab-left <?php echo ($this->staticType == 'climate')? 'current' : 'active'?>"></div>
            <div class="tab-center <?php echo ($this->staticType == 'climate')? 'current' : 'active'?>">
                <a href="<?php echo $this->baseUrl('discover-indonesia/climate') ?>">
                    <span class="href-nostyle"><?php echo $this->translate('id_static_climate') ?></span>
                </a>
            </div>
            <div class="tab-right <?php echo ($this->staticType == 'climate')? 'current' : 'active'?>"></div>
        </div>

        <div id="tab7">
            <div class="tab-left <?php echo ($this->staticType == 'peopleculture')? 'current' : 'active'?>"></div>
            <div class="tab-center <?php echo ($this->staticType == 'peopleculture')? 'current' : 'active'?>">
                <a href="<?php echo $this->baseUrl('discover-indonesia/peopleculture') ?>">
                    <span class="href-nostyle"><?php echo $this->translate('id_static_peopleculture') ?></span>
                </a>
            </div>
            <div class="tab-right <?php echo ($this->staticType == 'peopleculture')? 'current' : 'active'?>"></div>
        </div>

    </div>
    <!--end tab-->



