<!-- style css untuk halaman admin news -->
<?php $this->placeholder('styles')->captureStart(); ?>
    <link href="<?php echo $this->scriptUrl('/styles/table-css.php'); ?>" 
          rel="stylesheet" type="text/css" />
<?php $this->placeholder('styles')->captureEnd(); ?>

<!-- print out any message from create/saved page proccess-->
<?php 
    if (!empty($this->message)) {
        foreach ($this->message as $warn) echo $this->flashMessage($warn);
    }
?>

<!-- set page context -->
<h2>News Menu</h2>
<h3 class="wide">Create, Update, or Delete from the list</h3>

<div class="table-container">
    <input type="button" class="btn radius" style="margin-bottom: 10px;" 
           value="+ Add News" onclick="window.location='<?php echo $this->rootUrl('admin/news/create'); ?>'"/>
    
    <br class="clearfloat" />
        
    <!-- generating the filter panel and row show per page filter -->
    <?php $panel_data = array('year' => $this->year_list); ?>
    <?php echo $this->partial('news/filter-panel.phtml', $panel_data) . "\n"; ?>
    <?php echo $this->render('partial/page-filter.phtml'); ?>
    
    <!-- generating alert on filter selected -->
    <br class="clearfloat" />
    <?php if (!empty($this->alert)) : ?>
        <div class="tip"> Current filter selected: <?php echo $this->alert; ?>
        </div>
    <?php endif; ?> 
    
    <!-- if the paginator is not empty then print out the data -->
    <br class="clearfloat" />
    <?php if (count($this->paginator) > 0) : ?>
    
        <!-- print out the pagination control at the top of the table-->
        <?php echo $this->paginationControl($this->paginator, 'Sliding',
                                    'partial/pagination-control.phtml'); ?>
        
        <br class="clearfloat" />

        <table style="width: 100%;" cellspacing="0">
            
            <?php echo $this->partial('news/table-header.phtml') . "\n"; ?>
            
            <tbody>
                <?php $row_index = 0; ?>
                <?php echo $this->partialLoop('news/table-row.phtml', 
                                                $this->paginator) . "\n"; ?>
            </tbody>
        </table>
        
        <!-- print out the pagination control at the bottom of the table -->
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 
                                    'partial/pagination-control.phtml'); ?>
        
        <br class="clearfloat" />
    <?php endif; ?>	
</div>

<div id="processLoader" class="hidden">
    <img src='<?php echo $this->imageUrl('ajax-loader-big.gif'); ?>'/>
</div>

<!-- start capturing the javascript -->
<?php
    $this->placeholder('jsInline')->captureStart();
?>

<script type="text/javascript">
	
    /**
     * IS: -
     * FS: Semua filter box tidak tertampil
     * Desc: Menyembunyikan seluruh filter
     */
    function hideAllFilter()
    {
        $('.poi-box').hide();
        $('.language-box').hide();
        $('.title-box').hide();
        $('.year-box').hide();
        $('.month-box').hide();
        $('.status-box').hide();
    }
    
    /**
     * IS: Tertampil hanya filter default 'Show All'
     * FS: Tertampil filter box tambahan sesuai pilihan
     * Desc: Mengganti tampilan filter
     */
    function filterSwitch(value)
    {   
        switch(value)
        {
            case "0": hideAllFilter();
                      break;
            case "1": hideAllFilter();
                      $('.title-box').fadeIn('slow');
                      break;
            case "2": hideAllFilter();
                      $('.poi-box').fadeIn('slow');
                      break;
            case "3": hideAllFilter();
                      $('.year-box').fadeIn('slow');
                      $('.month-box').fadeIn('slow');
                      break;
            case "4": hideAllFilter();
                      $('.status-box').fadeIn('slow');
                      break;
        }
    }
    
    /**
     * IS: News ada
     * FS: News tidak ada, dan dihapus dari basis data
     * Desc: Menghapus news, 
     *       send request via ajax for deleting the news into the table
     */
    function deleteNews(news_id)
    {
        if (confirm('Do you really want to delete this news?'))
        {
            tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
            $.ajax(
            {
                type: "POST",
                url: "<?php echo $this->rootUrl('/admin/ajax/deletenews'); ?>",
                data: {newsid:news_id}, 
                success: function(data)
                {
                    window.location.reload(true);
                },
                error: function()
                {
                    alert('Error occured, please report this to the developer');
                }
            });    
        }        
    }

    function deleteNews2(news_id)
    {
        if (confirm('Do you really want to delete this Indonesian Translation news?'))
        {
            tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
            $.ajax(
            {
                type: "POST",
                url: "<?php echo $this->rootUrl('/admin/ajax/deletenews2'); ?>",
                data: {newsid:news_id},
                success: function(data)
                {
                    window.location.reload(true);
                },
                error: function()
                {
                    alert('Error occured, please report this to the developer');
                }
            });
        }
    }

    /**
     * IS: Status news publish atau draft
     * FS: Status news berubah dari publish menjadi draft atau sebaliknya
     * Desc: Mengganti status news menjadi publish atau draft
     */
    function changeNewsStatus(news_id, obj, status)
    {
        if (confirm('Do you really want to change this news status?'))
        {
            tb_show("", 
            "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", 
            "");
            $.ajax(
            {
                type: "POST",
                url: 
                "<?php echo $this->rootUrl('/admin/ajax/hideshownews'); ?>",
                data: {newsid:news_id}, 
                success: function(data)
                {
                    obj.html(data);
                    tb_remove();
                    window.location.reload(true);
                },
                error: function()
                {
                    alert('Error Occured, please report this to the developer');
                }
            });
        }        
    }
    
$(function(){
    $('.filter-panel').show();
    
    $('.poi-box').autocomplete("<?php echo $this->rootUrl('/admin/ajax/poiautocomplete'); ?>",
    {
        minChars: 2,
        width: 180,
    	selectFirst: false,
        loaderImage: "<?php echo $this->imageUrl('mini-loader.gif'); ?>"
    });
});
</script>
    
<?php $this->placeholder('jsInline')->captureEnd(); ?>