<div id="social-network">

    

        <iframe id="fb" src="http://www.facebook.com/plugins/like.php?href=<?php echo $this->currentUrl();?>&amp;layout=button_count&amp;show_faces=false&amp;width=450&amp;action=like&amp;font&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:200px; height:21px;" allowTransparency="true"></iframe>

      

        <a href="#"

            url = "<?php echo $this->currentUrl();?>"

            class="twitter-share-button"

            data-count="horizontal">Tweet</a>

        <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>

      

        

        <!--google+-->

        <!-- Place this tag where you want the +1 button to render. -->

        <div class="g-plusone" data-annotation="inline" data-width="300" data-href="https://plus.google.com/u/0/b/105485413132575433204/105485413132575433204"></div>

    

        <!-- Place this tag after the last +1 button tag. -->

        <script type="text/javascript">

        (function() {

            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;

            po.src = 'https://apis.google.com/js/plusone.js';

            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);

        })();

        </script>

        <!--end of google +-->  

        

        <?php //echo $this->shareSave(); ?>

        

        <!-- AddThis Button BEGIN -->

        <a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=300&amp;pubid=ra-50ac942b7aa06521"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" style="margin-top:-1em;width:125px;height:16px;margin-left:-80px;" alt="Bookmark and Share" style="border:0"/></a>

        <script type="text/javascript">var addthis_config = {"data_track_addressbar":false};</script>

        <script type="text/javascript" src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-50ac942b7aa06521"></script>

        <!-- AddThis Button END -->

    

   

</div>



