<!--
 * RelatedLinkViewer
 *
 * Viewer untuk halaman Related Link
 *
 * @copyright Copyright (c) 2010 Sangkuriang Studio
 * @author Sangkuriang Studio <www.sangkuriangstudio.com>
 -->
<div class="section">
    
    <h2 class="section-title">
        <span><?php echo $this->translate('id_menu_link'); ?></span>
    </h2>
    <?php echo $this->categorylist?>
    <?php echo $this->paginationControl(
            $this->relatedlink,
            'Sliding',
            'partials/pagination.phtml',
            array('message' => $this->customName, 'upMessage' => true)); ?>
    
    <div style="margin-left: 80px; margin-right: 50px;">
    <?php foreach($this->relatedlink as $link) : ?>
        <div class="en-list">
            <h3 style="font-weight: bold">
                <?php echo $link['title']; ?>
            </h3>
            <br />

            <?php echo $link['description']; ?>
            <?php $rellink = substr($link['link'], 0,5); ?>
            <?php if (!empty ($link['link'])) : ?>
                <?php if($rellink == "http:"){?>
                <p><?php echo $this->translate('id_go_to_link'); ?><a href="<?php echo $link['link']; ?>">
                    <?php echo $link['link']; ?>
                    </a>
                </p>
                <?php } else { ?>
                <p><?php echo $this->translate('id_go_to_link'); ?><a href="http://<?php echo $link['link']; ?>">
                    <?php echo $link['link']; ?>
                    </a>
                </p>
                <?php } ?>
            <?php endif; ?>
                
            <div class="clear-left"></div>
            
        </div>
    <?php endforeach; ?>
    </div>

    <?php echo $this->paginationControl(
            $this->relatedlink,
            'Sliding',
            'partials/pagination.phtml',
            array('message' => $this->customName, 'downMessage' => true)); ?>
</div>
 <script>
	function filter(category){
		window.location = "<?php echo $this->baseUrl()?>/related-links/index/category/" + category;
	}

</script>