<?php $this->placeholder('styles')->captureStart(); ?>
<link href="<?php echo $this->scriptUrl('/styles/table-css.php'); ?>" rel="stylesheet" type="text/css" />
<?php $this->placeholder('styles')->captureEnd(); ?>

<!-- print out any message from create/saved page proccess-->
<?php 
    if (!empty($this->message)) {
        foreach ($this->message as $warn) echo $this->flashMessage($warn);
    }
?>
    
<h2>Tourism Operator Indonesian Menu</h2>
<h3 class="wide">Create, Update, or Delete from the list</h3>
<div class="table-container"/>
    <input type="button" class="btn radius" style="margin-bottom:10px;" value="+ Add Tourism Operator Indonesian" onclick="window.location='<?php echo $this->rootUrl('admin/tourismoperatorindo/create'); ?>'"/>
    <br class="clearfloat"  />
    <?php $panel_data = array('class' => $this->classification_list,'island' => $this->island_list); ?>
    <?php echo $this->partial('tourismoperatorindo/filter-panel.phtml',$panel_data)."\n"; ?>
	<?php echo $this->render('partial/page-filter.phtml'); ?>
    
    <!-- generating alert on filter selected -->
    <br class="clearfloat" />
    <?php if (!empty($this->alert)) : ?>
        <div class="tip"> Current filter selected: <?php echo $this->alert; ?>
        </div>
    <?php endif; ?> 
    
    <br class="clearfloat"  />
    <?php if(count($this->paginator)>0) :?>
			<?php echo $this->paginationControl($this->paginator,'Sliding','partial/pagination-control.phtml'); ?>
            <br class="clearfloat"  />
            <table style="width:100%;" cellspacing="0">
            <?php echo $this->partial('tourismoperatorindo/table-header.phtml')."\n"; ?>
                <tbody>
                    <?php $row_index = 0; ?>                        
		            <?php echo $this->partialLoop('tourismoperatorindo/table-row.phtml',$this->paginator)."\n"; ?>
                </tbody>
            </table>
			<?php echo $this->paginationControl($this->paginator,'Sliding','partial/pagination-control.phtml'); ?>
            <br class="clearfloat"  />
	<?php endif; ?>
    <br class="clearfloat"  />
</div>
<div id="processLoader" class="hidden">
   <img src='<?php echo $this->imageUrl('ajax-loader-big.gif'); ?>'/>
</div>

<?php 
	$this->placeholder('jsInline')->captureStart();
?>
<script type="text/javascript">
    function deleteTourism(tourism_id)
    {
       if(confirm('Are you sure you want to delete this tourismoperator?'))
       {
        tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->rootUrl().'/admin/ajax/deletetourism'; ?>",
            data: {tourismid:tourism_id},
            success: function(data){
                window.location.reload(true);
            },
            error: function(){
                alert('Error Occured Please Report to the Developer!');
            }
        });
       } 
    }

    function deleteTourism2(tourism_id)
    {
       if(confirm('Are you sure you want to delete this Indonesian translation tourismoperator?'))
       {
        tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->rootUrl().'/admin/ajax/deletetourism2'; ?>",
            data: {tourismid:tourism_id},
            success: function(data){
                window.location.reload(true);
            },
            error: function(){
                alert('Error Occured Please Report to the Developer!');
            }
        });
       }
    }

    function deleteTourismEnglish(tourism_id)
    {
       if(confirm('Are you sure you want to delete this English translation tourismoperator?'))
       {
        tb_show("", "#TB_inline?height=25&width=210&inlineId=processLoader&modal=true", "");
        $.ajax({
            type: "POST",
            url: "<?php echo $this->rootUrl().'/admin/ajax/deletetourismenglish'; ?>",
            data: {tourismid:tourism_id},
            success: function(data){
                window.location.reload(true);
            },
            error: function(){
                alert('Error Occured Please Report to the Developer!');
            }
        });
       }
    }

    function hideAllFilter()
    {
        $('.name-box').hide();
        $('.classification-box').hide();
        $('.area-box').hide();
    }
    
    function filterSwitch(value)
    {   
                
        switch(value)
        {
            case "0": hideAllFilter();
                      break;  
            case "3": hideAllFilter();
                      $('.area-box').fadeIn('slow');
                      $('.filter-btn').fadeIn('slow');
                      break;
            case "2": hideAllFilter();
                      $('.classification-box').fadeIn('slow');
                      $('.filter-btn').fadeIn('slow');
                      break;
            case "1": hideAllFilter();
                      $('.name-box').fadeIn('slow');
                      $('.filter-btn').fadeIn('slow');
                      break;
        }
    }
    
    $(function(){
        $('.filter-panel').show();
    });
</script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>