    <table width="100%" style="margin-bottom:12px;">    
      <tr><td><div id="searchcontrol">Searching by keyword : <label id="keyWord" style="font-weight:bold"></label></div></td></tr>
      <tr><td><span id="searchresult"><a name="top"></a></span></td></tr>
    </table>
    <div id="tabbed_box_1" class="tabbed_box">        
        <div class="tabbed_area">
            <ul class="tabs" id="tabs">
                <li><a href="#top" id="news" class="tabsearch active">News</a></li>
                <li><a href="#top" id="event" class="tabsearch">Events</a></li>
                <li><a href="#top" id="dest" class="tabsearch">Destinations</a></li>
                <li><a href="#top" id="article" class="tabsearch">Article</a></li>
                <li><a href="#top" id="gallery" class="tabsearch">Gallery</a></li>
                <li><a href="#top" id="tourism" class="tabsearch">Tourism Operator</a></li>
            </ul>
            <?php if($this->emptyResult) :?>
                <div class="contentEmpty">
                    <?php echo $this->emptyResult;?>
                </div>

            <?php else :?>
                <div id="content_news" class="content">
                    <ul id="news_content">
                        <?php echo $this->news;?>
                    </ul>
                </div>
    
                <div id="content_event" class="content">
                    <ul id="event_content">
                        <?php echo $this->event;?>
                    </ul>
                </div>
    
                <div id="content_dest" class="content">
                    <ul id="dest_content">
                        <?php echo $this->destination;?>
                    </ul>
                </div>  
    
    
                <div id="content_article" class="content" style="display:none">
                    <ul id="article_content">
                        <?php echo $this->article;?>
                    </ul>
                </div>  
    
                <div id="content_gallery" class="content" style="display:none">
                    <ul id="gallery_content">
                        <?php echo $this->gallery;?>
                    </ul>
                </div>
    
                <div id="content_tourism" class="content" style="display:none">
                    <ul id="tourism_content">
                        <?php echo $this->taorismOperator;?>
                    </ul>
                </div>
            
            <?php endif;?>

            <div class="paging">
                <div class="navigation" id="nav_news">
                   <input disabled="disabled" class="first passive" id="firsts_news" type="button" value="first"/>
                   <input disabled="disabled" class="prev passive" id="prev_news" type="button" value="prev"/>
                        <div class="linkpages" id="linkpage_news" style="float:left" title="news">
                            <?php echo $this->linkpage_news;?>
                        </div>
                   <input class="next" id="next_news" type="button" value="next"/>
                   <input class="last" id="last_news" type="button" value="last"/>

                </div>
                
                <div class="navigation" id="nav_event" style="display:none">
                   <input disabled="disabled" class="first passive" id="firsts_event" type="button" value="first"/>
                   <input disabled="disabled" class="prev passive" id="prev_event" type="button" value="prev"/>

                        <div class="linkpages" id="linkpage_event" style="float:left;display:none;" title="event">
                            <?php echo $this->linkpage_event;?>
                        </div>

                   <input class="next" id="next_event" type="button" value="next"/>
                   <input class="last" id="last_event" type="button" value="last"/>
                </div>
                
                <div class="navigation" id="nav_dest" style="display:none">
                   <input disabled="disabled" class="first passive" id="firsts_dest" type="button" value="first"/>
                   <input disabled="disabled" class="prev passive" id="prev_dest" type="button" value="prev"/>
                        <div class="linkpages" id="linkpage_dest" style="float:left;display:none;" title="dest">
                           <?php echo $this->linkpage_dest;?>
                       </div>
                   <input class="next" id="next_dest" type="button" value="next"/>
                   <input class="last" id="last_dest" type="button" value="last"/>
                </div>

                <div class="navigation" id="nav_article" style="display:none">
                   <input disabled="disabled" class="first passive" id="firsts_article" type="button" value="first"/>
                   <input disabled="disabled" class="prev passive" id="prev_article" type="button" value="prev"/>
                        <div class="linkpages" id="linkpage_article" style="float:left;display:none;" title="article">
                            <?php echo $this->linkpage_article;?>
                        </div>
                   <input class="next" id="next_article" type="button" value="next"/>
                   <input class="last" id="last_article" type="button" value="last"/>
                </div>

                <div class="navigation" id="nav_gallery" style="display:none">
                   <input disabled="disabled" class="first passive" id="firsts_gallery" type="button" value="first"/>
                   <input disabled="disabled" class="prev passive" id="prev_gallery" type="button" value="prev"/>
                        <div class="linkpages" id="linkpage_gallery" style="float:left;display:none;" title="gallery">
                            <?php echo $this->linkpage_gallery;?>
                        </div>
                   <input class="next" id="next_gallery" type="button" value="next"/>
                   <input class="last" id="last_gallery" type="button" value="last"/>
                </div>

                <div class="navigation" id="nav_tourism" style="display:none">
                   <input disabled="disabled" class="first passive" id="firsts_tourism" type="button" value="first"/>
                   <input disabled="disabled" class="prev passive" id="prev_tourism" type="button" value="prev"/>
                        <div class="linkpages" id="linkpage_tourism" style="float:left;display:none;" title="tourism">
                            <?php echo $this->linkpage_tourism;?>
                        </div>
                   <input class="next" id="next_tourism" type="button" value="next"/>
                   <input class="last" id="last_tourism" type="button" value="last"/>
                </div>


           </div>              
        </div>                
    </div>

<!--news param nav-->
<input type="hidden" id="paramlast_news" title="last_news" value="<?php echo $this->totalpage_news;?>" />
<input type="hidden" id="offset_news" title="offset_news" value="<?php echo $this->offset;?>" />
<input type="hidden" id="curpage_news" title="curpage_news" value="1" />
<input type="hidden" id="allpage_news" title="allpage_news" value="<?php echo $this->totalpage_news;?>" />
<input type="hidden" id="param_news" title="param_news" value="<?php echo $this->param;?>" />
<input type="hidden" id="first_news" title="first_news" value="1" />
<!--end news param nav-->
<br />
<br />

<!--event param nav-->
<input type="hidden" id="paramlast_event" title="last_event" value="<?php echo $this->totalpage_event;?>" />
<input type="hidden" id="offset_event" title="offset_event" value="<?php echo $this->offset;?>" />
<input type="hidden" id="curpage_event" title="curpage_event" value="1" />
<input type="hidden" id="allpage_event" title="allpage_event" value="<?php echo $this->totalpage_event;?>" />
<input type="hidden" id="param_event" title="param_event" value="<?php echo $this->param;?>" />
<input type="hidden" id="first_event" title="first_event" value="1" />
<!--end event param nav-->
<br />
<br />

<!--dest param nav-->

<input type="hidden" id="paramlast_dest" title="last_dest" value="<?php echo $this->totalpage_dest;?>" />
<input type="hidden" id="offset_dest" title="offset_dest" value="<?php echo $this->offset;?>" />
<input type="hidden" id="curpage_dest" title="curpage_dest" value="1" />
<input type="hidden" id="allpage_dest" title="allpage_dest" value="<?php echo $this->totalpage_dest;?>" />
<input type="hidden" id="param_dest" title="param_dest" value="<?php echo $this->param;?>" />
<input type="hidden" id="first_dest" title="first_dest" value="1" />
<!--enddest param nav-->
<br />
<br />

<!--article param nav-->
<input type="hidden" id="paramlast_article" title="last_article" value="<?php echo $this->totalpage_article;?>" />
<input type="hidden" id="offset_article" title="offset_article" value="<?php echo $this->offset;?>" />
<input type="hidden" id="curpage_article" title="curpage_article" value="1" />
<input type="hidden" id="allpage_article" title="allpage_article" value="<?php echo $this->totalpage_article;?>" />
<input type="hidden" id="param_article" title="param_article" value="<?php echo $this->param;?>" />
<input type="hidden" id="first_article" title="first_article" value="1" />
<!--end article param nav-->
<br />
<br />

<!--galley param nav-->
<input type="hidden" id="paramlast_gallery" title="last_gallery" value="<?php echo $this->totalpage_gallery;?>" />
<input type="hidden" id="offset_gallery" title="offset_gallery" value="<?php echo $this->offset;?>" />
<input type="hidden" id="curpage_gallery" title="curpage_gallery" value="1" />
<input type="hidden" id="allpage_gallery" title="allpage_gallery" value="<?php echo $this->totalpage_gallery;?>" />
<input type="hidden" id="param_gallery" title="param_gallery" value="<?php echo $this->param;?>" />
<input type="hidden" id="first_gallery" title="first_gallery" value="1" />
<!--end gallery param nav-->
<br />
<br />

<!--tourism param nav-->
<input type="hidden" id="paramlast_tourism" title="last_tourism" value="<?php echo $this->totalpage_tourism;?>" />
<input type="hidden" id="offset_tourism" title="offset_tourism" value="<?php echo $this->offset;?>" />
<input type="hidden" id="curpage_tourism" title="curpage_tourism" value="1" />
<input type="hidden" id="allpage_tourism" title="allpage_tourism" value="<?php echo $this->totalpage_tourism;?>" />
<input type="hidden" id="param_tourism" title="param_tourism" value="<?php echo $this->param;?>" />
<input type="hidden" id="first_tourism" title="first_tourism" value="1" />
<!--end tourism param nav-->
<br />

<?php $this->placeholder('jsInline')->captureStart(); ?>

<script type="text/javascript">
$(document).ready(function(){

    $('#keyWord').text('<?php echo $this->param;?>');

    var url = "<?php echo $this->baseUrl('/search/');?>";
    var limit = "<?php echo $this->limit?>";
    
    //function in search.js
    ajaxPagination(url,limit);
});
</script>
<?php $this->placeholder('jsInline')->captureEnd(); ?>