  <div id="topnav"class="topnav">
      <div id="country-select">
                <dl id="target" class="dropdown">
                    <dt>
                    <span class="flag">
                        <a href="#"><em><img src="<?php echo $this->imageUrl('/flag-' . Zend_Registry::get('language') . '.png') ?>" alt="flag" /><?php //echo strtoupper(Zend_Registry::get('language')); ?></em></a></span>
                    </dt>
                    <dd>
                        <ul>
                            <li class="id"><a href="http://localhost/lamanbudaya/public/id"><span class="flag"><em>ID</em></span></a></li>
                            <li class="en"><a href="http://localhost/lamanbudaya/public/en"><span class="flag"><em>EN</em></span></a></li>
                        </ul>
                      </dd>
                    </dl>
                  </div>
      
     <?php echo $this->translate('sign_in'); ?><a href="login"class="signin"><span>Sign in</span></a> 
      
  </div>
  <fieldset id="signin_menu">
    <form method="post"id="signin"action="https://twitter.com/sessions">
      <label for="username">Username or email</label>
      <input id="username"name="username"value=""title="username"tabindex="4"type="text">
      </p>
      <p>
        <label for="password">Password</label>
        <input id="password"name="password"value=""title="password"tabindex="5"type="password">
      </p>
      <p class="remember">
        <input id="signin_submit"value="Sign in"tabindex="6"type="submit">
        <input id="remember"name="remember_me"value="1"tabindex="7"type="checkbox">
        <label for="remember">Remember me</label>
      </p>
      <div class="fb-login-button" data-show-faces="true" data-width="200" data-max-rows="1"></div>
      <p class="forgot"> <ahref="#"id="resend_password_link">Forgot your password?</a> </p>
      <p class="forgot-username"> <Aid=forgot_username_link 
title="If you remember your password, try logging in with your email"
href="#">Forgot your username?</A> </p>
    </form>
  </fieldset>
  
  
<?php $this->placeholder('jsInline')->captureStart(); ?>
<script src="javascripts/jquery.js" type="text/javascript"></script>
<script type="text/javascript">
        $(document).ready(function() {

            $(".signin").click(function(e) {
                e.preventDefault();
                $("fieldset#signin_menu").toggle();
                $(".signin").toggleClass("menu-open");
            });

            $("fieldset#signin_menu").mouseup(function() {
                return false
            });
            $(document).mouseup(function(e) {
                if($(e.target).parent("a.signin").length==0) {
                    $(".signin").removeClass("menu-open");
                    $("fieldset#signin_menu").hide();
                }
            });            

        });
</script>

<?php $this->placeholder('jsInline')->captureEnd(); ?>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=	493949460635877";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>